### ISSUE TITLE
Chart gets focus (trackball, trackinfo) on legend area

### ISSUE THREAD

**Issue by orchowski** [telerik/UI-For-UWP#112]
I attached the screenshot
![screen](https://user-images.githubusercontent.com/17548765/26963902-60ac297c-4cef-11e7-9f20-09e10b7f52c2.PNG)

**Comment by APopatanasov** [comment]
Hi @orchowski ,
Could you please provide a sample with your exact Chart declaration that reproduces the issue?

**Comment by orchowski** [comment]
@APopatanasov 
I'll do this on Monday.
You can observe this only after zoom in horizontal axis.

**Comment by orchowski** [comment]
Hi, @APopatanasov 
Ok, [here](https://github.com/orchowski/ChartFocusBug-Example) you have test project to see that.
Problem occurs on Anniversary update and Creators update too.

**Comment by APopatanasov** [comment]
@orchowski  Thanks for the provided sample. I as able to reproduce the described behavior. I will need some more time to check the scenario completely - as soon as I have some information about the issue I will let you know.

**Comment by APopatanasov** [comment]
We were able to found the cause of the issue and a fix will be applied in the next few days.  😄
