### ISSUE TITLE
Allow custom columns

### ISSUE THREAD

**Issue by dotMorten** [telerik/UI-For-UWP#122]
You can't currently inherit from DataGridColumn, since it contains several internal abstract members.
To simplify column creation for certain types, it would be much easier to be able to create your own columns by overriding `CreateContainer` and return your own framework element.

**Comment by APopatanasov** [comment]
Hi @dotMorten ,
For such scenarios where the content of the cell needs to be customized with a specific FrameworkElement the Template Column could be used:
[http://docs.telerik.com/devtools/universal-windows-platform/controls/raddatagrid/columns/datagrid-templatecolumn](http://docs.telerik.com/devtools/universal-windows-platform/controls/raddatagrid/columns/datagrid-templatecolumn)

Could you please give it a try?

**Comment by dotMorten** [comment]
@APopatanasov I'm well aware of template columns, but these don't let you run more customized code tailored for certain types, where you return which set of controls you want based on logic. The only thing you can return there are data templates, which can't be created at runtime.

**Comment by APopatanasov** [comment]
Thanks for the provided additional information of your scenario. We accept your suggestion for feature.
