### ISSUE TITLE
When item from the DataGridComboBoxColumn gets selected the selection box of the ComboBox becomes empty

### ISSUE THREAD

**Issue by APopatanasov** [telerik/UI-For-UWP#124]
When a selection is performed the selected item is not properly visualized inside the selection box of the ComboBox - it is visualized as empty. It is reproduced randomly. PR -> #126

**Comment by kalintodorov** [comment]
Fixna li go Nase?

On Jun 19, 2017 17:32, Atanas Popatanassov <notifications@github.com> wrote:

When a selection is performed the selected item is not properly visualized inside the selection box of the ComboBox - it is visualized as empty. It is reproduced randomly.
