### ISSUE TITLE
CanUserChooseColumns in RadDataGrid control doesn't show verticall scroll

### ISSUE THREAD

**Issue by ashiqhassan95** [telerik/UI-For-UWP#140]
There is good option in RadDataGrid that is CanUserChooseColumns which allow user to show/hide columns in RadDataGrid. But when number of columns is more, it doesn't show full of those columns items because unavailability vertical scrolling. Please implement scrollviewer in that right pane which show/hide columns.
![snip_20170704121725](https://user-images.githubusercontent.com/2870845/27818522-995636d2-60b3-11e7-9853-bb62a91d2d37.png)

**Comment by APopatanasov** [comment]
Hi @ashiqhassan95 ,

Thanks for binding this to our attention. Until that feature gets implemented you could simply modify the default Template of the DataGridColumnsFlyout and add the desired ScrollViewer - thus you should be able to scroll as desired.

**Comment by ashiqhassan95** [comment]
Please can you tell me, How could I achieve that. It will be appreciated, if you provide code.

**Comment by APopatanasov** [comment]
The Template of the DataGridColumnsFlyout could be found on the following link:
[https://github.com/telerik/UI-For-UWP/blob/master/Controls/Grid/Grid.UWP/Themes/Resources.xaml#L725](https://github.com/telerik/UI-For-UWP/blob/master/Controls/Grid/Grid.UWP/Themes/Resources.xaml#L725)

You could copy the default Style inside your application and add the needed ScrollViewer inside the current Template of the flyout (before the Grid Panel for example) without changing the rest of the Template.

You could also try to work on this feature on your own and send us a pull request with the implementation - we will be glad to review it. 😃

**Comment by ashiqhassan95** [comment]
Thankyou. 😄

**Comment by phalouvas** [comment]
Hello. Is there any piece of code that we can make the scroll viewer work? I tried but seems impossible. I would appreciate any assistance.

**Comment by ashiqhassan95** [comment]
I couldn't achieved.. It is not possible.

**Comment by APopatanasov** [comment]
Attached you could find a sample project that demonstrates the described in my initial response approach. 

If you are interested on working on this feature you could implement it in the source code an send us a pull-request. Be aware that the suggested in the sample project in not fully tested and some improvements might need to be made.

[RadDataGrid_140.zip](https://github.com/telerik/UI-For-UWP/files/1252393/RadDataGrid_140.zip)

**Comment by ashiqhassan95** [comment]
Result was marvelous.. Thankyou so much...

**Comment by phalouvas** [comment]
Unfortunately is not working the code as is. I already tried what you attached. It does add the scrolling, but it shows columns up to the height of the active page. Normally there should be items below this height. Still your code gave me an idea that works.

If you add height in DataGridFlyoutPanel  meaning changing from: <localPrimitives:DataGridFlyoutPanel  to <localPrimitives:DataGridFlyoutPanel Height="1500"

Then it scroll and show all columns as expected. For my purpose a height of 1500 is enough, even thought this height should be somehow calculated. The actual change must be done in DataGridFlyoutPanel .

In any case, if you think this change is acceptable I can make a pull request. Thanks and wait for your feedback.

**Comment by APopatanasov** [comment]
Hi @phalouvas ,

As mentioned in my previous response the suggested approach is just one of many possible approaches that could be tested in order to find the best solution for that feature.

According to me the approach suggested by you with the set Height is too specific for your  scenario and might not be suitable and work for other scenarios with different amount of Columns - indeed some calculations needs to be made.

Feel free to send us a pull-request with your suggestions - we will review it and let you know whether it is a suitable one.
