### ISSUE TITLE
Chart control Axis properties on x86 breaks designer

### ISSUE THREAD

**Issue by crutkas** [telerik/UI-For-UWP#149]
We noticed this on Windows Template Studio but can isolate this with a file->new blank application so we verified that this is not a WTS issue.

What we're seeing is below:

- x86 - With cleaning the solution and compiling w/ x86, i see errors when viewing the chart page.
- x64 - With cleaning the solution and compiling w/ x64, the designer loads

The error when set to x86 on the file->new is: **Object reference not set to an instance of an object**

These errors are for the Axis: CategoricalAxis and LinearAxis.

Here is the basic sample for the file->new
```
        <tc:RadCartesianChart>
            <tc:RadCartesianChart.HorizontalAxis>
                <tc:CategoricalAxis />
            </tc:RadCartesianChart.HorizontalAxis>
            <tc:RadCartesianChart.VerticalAxis>
                <tc:LinearAxis />
            </tc:RadCartesianChart.VerticalAxis>
            <tc:BarSeries ShowLabels="True" />
        </tc:RadCartesianChart>
```

Our tracking issue is: https://github.com/Microsoft/WindowsTemplateStudio/issues/622

**Comment by APopatanasov** [comment]
Hi @crutkas ,

We will apply a fix shortly. Thanks for bringing this to our attention.

**Comment by crutkas** [comment]
i would hope someone would do the same for Windows Template Studio :)

**Comment by crutkas** [comment]
Awesome. Has a budget package update gone live?

**Comment by APopatanasov** [comment]
Hi @crutkas ,

We will upload a new package that will include the fix in short terms. I will write back to you once it become live.

**Comment by APopatanasov** [comment]
@crutkas The new version of the package is live. 😄
