### ISSUE TITLE
NullReferenceException with ChartTrackBallBehavior while chart in updating

### ISSUE THREAD

**Issue by vunder** [telerik/UI-For-UWP#154]
RadCartesianChart with LineSeries and ChartTrackBallBehavior raises an exception in case chart data are not ready yet but ChartTrackBallBehavior is present and user is moving mouse over the chart

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Telerik.UI.Xaml.Controls.Chart.ChartTrackBallBehavior.UpdateVisuals()
>    at Telerik.UI.Xaml.Controls.Chart.ChartTrackBallBehavior.HandleDrag(Point currentPosition)
>    at Telerik.UI.Xaml.Controls.Chart.ChartTrackBallBehavior.OnPointerEntered(PointerRoutedEventArgs args)
>    at Telerik.UI.Xaml.Controls.Chart.RadChartBase.NotifyPointerEntered(PointerRoutedEventArgs e)
>    at Telerik.UI.Xaml.Controls.Chart.RadChartBase

**Comment by APopatanasov** [comment]
@vunder Thanks for bringing this to our attention. A fill will be applied shortly.
