### ISSUE TITLE
Invalid character in PART_LoadButton for RadDataGrid

### ISSUE THREAD

**Issue by pcolmer** [telerik/UI-For-UWP#158]
The XAML that builds the explicit load button has this in it to define a graphic aspect of that button:

    <TextBlock FontFamily="{ThemeResource SymbolThemeFontFamily}" Text="&#xE0BA;" FontSize="18" RenderTransformOrigin="0.5,0.5" >
        <TextBlock.RenderTransform>
            <RotateTransform Angle="-90"/>
        </TextBlock.RenderTransform>
    </TextBlock>

Unfortunately, E0BA is not a valid character in Sego MDL2 (https://docs.microsoft.com/en-us/windows/uwp/style/segoe-ui-symbol-font) so an empty rectangle gets displayed instead.

I'm not completely sure which character was intended here. http://docs.telerik.com/devtools/universal-windows-platform/controls/raddatagrid/datavirtualization suggests a down arrow in a circle, but I'm not sure how that could be accomplished with a TextBlock, hence the issue rather than a fix.

**Comment by APopatanasov** [comment]
Hi @pcolmer ,

Thanks for bringing this to our attention. The set symbol (E0BA) is actually part of the Segoe UI symbols used by Windows 8. As Windows 10 uses the Segoe MDL2 for "SymbolThemeFontFamily" in order to achieve the desired icon the E1FD and EA3A could be drawn on top of each other:
`  <primitivesCommon:InlineButton.Content>
                                    <Grid>
                                        <Grid.ColumnDefinitions>
                                            <ColumnDefinition/>
                                            <ColumnDefinition/>
                                        </Grid.ColumnDefinitions>
                                        <TextBlock FontFamily="{ThemeResource SymbolThemeFontFamily}"
                                                   Text="&#xE1FD;"
                                                   FontSize="12"
                                                   HorizontalAlignment="Center" 
                                                   VerticalAlignment="Center"
                                                   RenderTransformOrigin="0.5,0.5"/>
                                        <TextBlock FontFamily="{ThemeResource SymbolThemeFontFamily}" 
                                                   Text="&#xEA3A;" 
                                                   FontSize="20" 
                                                   RenderTransformOrigin="0.5,0.5"/>
                                        <TextBlock Grid.Column="1" Text="{Binding LoadMoreRowsText, RelativeSource={RelativeSource Mode=TemplatedParent}}" Margin="5 0 0 0"/>
                                    </Grid>
                                </primitivesCommon:InlineButton.Content>`

You can apply this on your side and see the visualized combine icon. We will apply a fix soon.

**Comment by APopatanasov** [comment]
As a more easier approach you could simply change the FontFamily to Segoe UI Symbol:
` <TextBlock FontFamily="Segoe UI Symbol" Text="&#xE0BA;" FontSize="18" RenderTransformOrigin="0.5,0.5" >`

Hope this will help you.
