### ISSUE TITLE
RadDataGrid duplicates display of rows when incremental loading is explicit

### ISSUE THREAD

**Issue by pcolmer** [telerik/UI-For-UWP#159]
Please see the attached example application. When you run the app and click on "load more rows", the grid fills with data generated as a result of the call to the incremental loading collection. In testing, the first load is 24 rows. However, the grid actually displays those 24 rows twice over:

![capture](https://user-images.githubusercontent.com/1979931/29003900-2a9d352e-7ab7-11e7-9b35-9e59c428b2d9.PNG)

If you scroll down and click on "load more rows" again, more rows are added as phase 1 (34 when I tested it) but, again, the rows added in phase 1 are displayed twice!

This doesn't happen in auto mode but I want to use explicit mode.

[App1.zip](https://github.com/telerik/UI-For-UWP/files/1203123/App1.zip)

**Comment by APopatanasov** [comment]
Hi @pcolmer ,

Thank you for the detailed information and for the provided sample application. I was able to reproduce the described by you issue. However, I will need some more time in order to investigate it further, so I could found the root cause of the issue. 

As soon as I have some more information I will let you know. If you are interested on working and fixing the issue feel free to send us a pull request and we will be glad to review it.

**Comment by pcolmer** [comment]
Hi @APopatanasov 

I would love to fix it and I did spend several hours yesterday trying to figure out how DataGrid is working with the data but, ultimately, failed singularly, hence the bug report.

I'd like to get more involved in the code but I'm not a *great* C# programmer (I manage :) ) and the lack of comments or code documentation is, for me at least, a hindrance.

**Comment by APopatanasov** [comment]
Hi @pcolmer ,

I think I was able to find the reason for this issue. 

When items are added to the collection of the provider its ViewChanged event gets invoked. If the data is not completely loaded an update should be registered (using the UpdateService of the DataGrid) that will refresh the data once it is completely loaded and thus the items should be visualized as expected. So, basically the following code needs to be called from inside the ViewChanged event of the provider (placed inside the GridModel.Data.cs class):
`private void OnDataProviderViewChanged(object sender, ViewChangedEventArgs e)
{
	if (!this.IsDataReady)
	{
		this.GridView.UpdateService.RegisterUpdate((int)UpdateFlags.All);
		return;
	}
	...
}`

We will apply a fix soon. I really hope the provided information will be helpful for you.

**Comment by pcolmer** [comment]
Thank you for the fix and the information. If I run my test app with debug-built versions of the Telerik code and click to load more rows, the following assertion in GridModel.Data.cs is failing:

            if (!this.isDataProviderUpdating)
            {
                Debug.Assert(RadControl.IsInTestMode, "Flag not raised properly.");
                return;
            }

Are you able to reproduce that? Is that a problem with my code or with the DataGrid code?

**Comment by APopatanasov** [comment]
@pcolmer You shouldn't have any concerns about the observed by your assertion. It is used for debug purposes - you could comment it if you want to prevent your application from stop running.

Could you please provide some more information about the fix? Are the items now loaded as expected when you apply the fix?

**Comment by pcolmer** [comment]
@APopatanasov I can confirm that the fix stops the duplicated display of items. However, I am noticing that after new data is loaded, the grid sometimes isn't displaying the crossover between the last old row and the first new row. In other words, I would expect the grid to be displaying the last row I saw just above the "load more rows" button followed by the first row of the next data. However, sometimes the grid is showing older rows and sometimes it is showing completely new rows. It doesn't seem be consistent.

The reason I was asking about the assertion is because I'm trying to debug a different problem I experience if I use auto mode instead of explicit. I wasn't sure if that assertion failure was highlighting a problem in my code.

**Comment by APopatanasov** [comment]
@pcolmer I am not exactly sure that I completely understand the described by you issue. Could you please, provide some more detailed information - a sample that reproduces it or a video that demonstrates it will be of great help? 

If the issue is no longer connected with the current issue you could open a new one describing it in details.

**Comment by pcolmer** [comment]
The issue is probably being uncovered now that you've resolved the display of items being loaded. I'll create a new issue and describe it more carefully.
