### ISSUE TITLE
Too many points in RadCartesianChart not lined up correctly

### ISSUE THREAD

**Issue by haefele** [telerik/UI-For-UWP#200]
I'm using the RadCartesianChart to show a simple chart, a double value on the Y axis, a date on the X axis.
But it seems that if I add too many of these points to the chart, the points will not be lined up correctly.
I'm also using the zoom functionality of the chart control, but I'm not sure yet what is causing the issue.

Here is a screenshot where I have exactly 30 points in the chart.
And you can see, all the points line up perfectly with the vertical dotted lines in the background.

![image](https://user-images.githubusercontent.com/2983790/32965827-1ba79d08-cbd8-11e7-8ace-391918214b8a.png)

Even if I zoom in really far, they still line up perfectly.

![image](https://user-images.githubusercontent.com/2983790/32965848-2db293ea-cbd8-11e7-94d2-72c47f9a19d3.png)

But once I add one more point, they start to be positioned incorrectly.

![image](https://user-images.githubusercontent.com/2983790/32965909-69e53976-cbd8-11e7-9ee2-d9d0c2a46f76.png)

One more time, but zoomed in.

![image](https://user-images.githubusercontent.com/2983790/32965920-771757aa-cbd8-11e7-81a7-1457c11bc854.png)

I've created a [gist here](https://gist.github.com/haefele/b3f079b95696df3c78f7ca15a19fa638) with all the source-code to reproduce the issue.

I'm currently running windows version 16299.64, but the error also appeared previously in the creators update 15063.

**Comment by haefele** [comment]
Phew, I was investigating this issue for a while now. And sadly it seems like its "by design"?

It all boils down to `DateTimeContinuousAxisModel.maxTickCount` [here](https://github.com/telerik/UI-For-UWP/blob/c1d7628f579e9ff4b89a0d5e2fb7616f3633a657/Controls/Chart/Chart.UWP/Engine/Axes/Continuous/DateTimeContinuousAxisModel.cs#L50).
If I have more points than the `maxTickCount` then the `tickInterval` [here](https://github.com/telerik/UI-For-UWP/blob/c1d7628f579e9ff4b89a0d5e2fb7616f3633a657/Controls/Chart/Chart.UWP/Engine/Axes/Continuous/DateTimeContinuousAxisModel.cs#L681) will be greater than 1 day, which again will make the `majorStep` [here](https://github.com/telerik/UI-For-UWP/blob/c1d7628f579e9ff4b89a0d5e2fb7616f3633a657/Controls/Chart/Chart.UWP/Engine/Axes/Continuous/DateTimeContinuousAxisModel.cs#L685) value greater than 1 day as well.
Then, when the horizontal axis ticks are created [here](https://github.com/telerik/UI-For-UWP/blob/c1d7628f579e9ff4b89a0d5e2fb7616f3633a657/Controls/Chart/Chart.UWP/Engine/Axes/Continuous/DateTimeContinuousAxisModel.cs#L431), it will skip a step at some point.

And that makes the points not align with the vertical axis ticks.

Soooo, as I said, seems like it is "by design"?

**Comment by APopatanasov** [comment]
Hi @haefele ,

You observations are pretty much correct. However, you can still achieve the desired alignment. The "maxTickCount" could easily be altered and modified using the **MaximumTicks** property of the **DataTimeContinuousAxis**. For example in your case if you set the value of that property to 32 the points will be aligned as desired:
`<chart:DateTimeContinuousAxis LabelFormat="{}{0:dd. MMM.}"
                                MaximumTicks="32"
                                PlotMode="OnTicksPadded" />`

Please, give it a try and let me know if it is working for you, so I can close the issue. 😄

**Comment by haefele** [comment]
Hey @APopatanasov ,

Yeah, I figured that much then as well. But I'm still... unhappy with that solution.
Because in the end, the diagram is incorrect if I have more points than specified on `MaximumTicks`, the points are just not aligned correctly...

**Comment by APopatanasov** [comment]
@haefele This is the how the control is implemented with its current implementation. Due to that implementation the MaximumTicks property has been introduced in order to control the observed by you behavior. 

If you have a desire feel free to improve the current implementation and make a pull request. I will be very glad to review it and if the control behaves better I will merge it. 

If you have any concerns or questions about the Chart's implementation and code feel free to ask.
