### ISSUE TITLE
Change RadDataGrid header

### ISSUE THREAD

**Issue by hupo376787** [telerik/UI-For-UWP#201]
I tried to change the column header to Chinese words after loading data and set datacontext, but vs said columns count is 0,
`radDataGrid.Columns[0].Header = "序号";`
Is there any other way?

And I also want to change the GroupPanel text to Chinese.

![default](https://user-images.githubusercontent.com/14960168/32990593-fd48db2a-cd66-11e7-9eb7-2041b581e348.jpg)

**Comment by APopatanasov** [comment]
Hi @hupo376787 ,

When exactly do you try to change the Header? The DataGrid needs a time to generate its columns after the DataContext is set. What I could suggest you is either to try to change the Header using the [GenerateColumn ](https://docs.telerik.com/devtools/universal-windows-platform/controls/raddatagrid/features/commands/datagrid-generatecolumncommand)command or to set the AutoGenerateColumns property to false and declare the columns in Xaml - thus you will be able to set their Headers as desired. Attached is a sample project that demonstrates both suggestions.

About your questions for the GroupPanel you can easily change the text using the [GridLocalizationManager ](https://docs.telerik.com/devtools/universal-windows-platform/common/localization/windows8-xaml-howtolocalize)- the example demonstrates that as well.

If that works for you please, close the issue if you don't have any questions. 😄 
[RadDataGridUWP_201.zip](https://github.com/telerik/UI-For-UWP/files/1486984/RadDataGridUWP_201.zip)

**Comment by hupo376787** [comment]
Hi @APopatanasov ,

The code works, but I can't fully understand it. As the code shows, it changes all column header to "序号". I want to specify each to a different header. But I don't know how, can u tell me, thx.

`Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, () => context.Result.Header = "序号");`

![default](https://user-images.githubusercontent.com/14960168/33020426-3819f61c-ce39-11e7-8543-755313acc243.jpg)

**Comment by APopatanasov** [comment]
@hupo376787 the GenerateColumn command is invoked for each column. The Result property of the context is actually the column itself. You can implement your own custom logic to recognize the columns (for example using their PropertyName property) and set the desired header using the demonstrated approach. 

I also suggest you to consider using the second approach with the defined in xaml columns - it is a more straight forward approach as you are declaring the columns and setting the Headers is more clear.

Please, also be aware that the UI for UWP team does not provide formal support, except to those customers who have purchased [a commercial license for UI for UWP](https://www.telerik.com/universal-windows-platform-ui). Please do not create support requests for this project in the issues list for this repo, as these will be immediately closed. You'll be directed to post your question on a community forum.

**Comment by hupo376787** [comment]
Hi, I have a premium key, which is given by Microsoft.

**Comment by APopatanasov** [comment]
If you have a license you can use [the commercial Telerik UI for UWP support channel](http://www.telerik.com/account/support-tickets/my-support-tickets.aspx) or the [forum channel ](https://www.telerik.com/forums/ui-for-universal-windows-platform) to submit a support ticket. 

As mentioned in my previous response the issues list should not be used for support requests - only a valid issues connected with the controls should be logged to the list.

Hope the provided information will point you to the right direction in order to get the needed help.

**Comment by hupo376787** [comment]
@APopatanasov Thanks, got it.
