### ISSUE TITLE
RadDataGrid does not allow ScrollColumnIntoView with invisible columns

### ISSUE THREAD

**Issue by Nasawa** [telerik/UI-For-UWP#206]
I'm using filters on my RadDataGrid to only show certain subsets of data. As the number of columns can get fairly large even when filtered, I added a dialog to scroll the user directly to a column given the header text:

```
var result = await _searchDialog.ShowAsync();
if (result != ContentDialogResult.Secondary)
{
    var text = _searchDialog.Text;
    var column = DataGrid.Columns.FirstOrDefault(x => (string) x.Header == text);
    if (column != null && column.IsVisible)
    {
        DataGrid.ScrollColumnIntoView(column); // this line is the issue
        Log($"Finding column: {text}");
    }
    else
        Log($"Unable to find column: {text}");
}
```

The DataGrid will fail to scroll despite finding the column, and if I scroll manually afterwards, the following exception is thrown:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Telerik.UI.Xaml.Controls.Grid.IndexStorage.ValueForIndex(Int32 index, Boolean approximate)
   at Telerik.UI.Xaml.Controls.Grid.Model.GridModel.ScrollColumnIndexIntoView(ScrollIntoViewOperation`1 operation)
   at Telerik.UI.Xaml.Controls.Grid.Model.GridModel.<>c__DisplayClass143_0.<ScrollColumnIntoViewCore>b__0()
   at Telerik.UI.Xaml.Controls.Primitives.DelegateUpdate`1.Process()
   at Telerik.UI.Xaml.Controls.Primitives.
```

Please let me know if there is any additional data I can provide.

**Comment by Nasawa** [comment]
In case someone has this same issue, I've come up with a workaround (may not be the most elegant, but it's 2 in the morning):

```
private async void FindColumnButton_Click(object sender, RoutedEventArgs e)
{
    var result = await _searchDialog.ShowAsync();
    if (result != ContentDialogResult.Secondary)
    {
        var text = _searchDialog.Text;
        var column = DataGrid.Columns.FirstOrDefault(x => (string) x.Header == text);
        if (column != null && column.IsVisible)
        {
            var index = GetColumnIndex(column);
            DataGrid.ScrollColumnIntoView(DataGrid.Columns[index]);
            Log($"Finding column: {text}");
        }
        else
            Log($"Unable to find column: {text}");
    }
}

private int GetColumnIndex(DataGridColumn column)
{
    var index = 0;
    foreach (var c in DataGrid.Columns)
    {
        if (c != column && c.IsVisible)
            index++;
        else if (c == column)
            break;
    }
    return index;
}
```

This doesn't resolve the original issue, of course, but it circumvents the check for the columns using the default logic and uses the column's visible index instead.

**Comment by APopatanasov** [comment]
Hi @Nasawa ,

I have tried to reproduce the described issue using the provided code and description, but it seems everything is working as expected on my side. It is really strange how the workaround you have found out is working while the initial implementation is not as basically you are passing the same column.

Could you please, try to isolate the issue into a sample project and send it to me? Thus I will be able to investigate the issue further and provide you with some more detailed information what exactly is causing the exception.

I am looking forward to hearing from you.

**Comment by Nasawa** [comment]
I was able to recreate it on a new project. To simulate having more columns, I added properties called "Element0"..."Element99" to the included SampleOrder (it didn't seem to have the same behavior with only the SampleOrder columns. I'm not sure why). As with my previously mentioned project, attempting to scroll to a certain field programatically did nothing at first, then upon manual horizontal scrolling, crashed with an `IndexOutOfRangeException`.

Below are the modifications I made to the DataGridPage.xaml.cs:
```
public DataGridPage()
        {
            InitializeComponent();
            grid.DataBindingComplete += GridOnDataBindingComplete;
        }

        private void GridOnDataBindingComplete(object sender, DataBindingCompleteEventArgs dataBindingCompleteEventArgs)
        {
            var columns = grid.Columns;

            foreach (var column in columns)
            {
                column.Name = column.Header.ToString();
                column.IsVisible = false;
            }

            columns["Element91"].IsVisible = true;
            columns["Element88"].IsVisible = true;
            columns["Element61"].IsVisible = true;
            columns["Element29"].IsVisible = true;
            columns["Element34"].IsVisible = true;
            columns["Element56"].IsVisible = true;
            columns["Element94"].IsVisible = true;
            columns["Element16"].IsVisible = true;
            columns["Element2"].IsVisible = true;
            columns["Element64"].IsVisible = true;
            columns["Element31"].IsVisible = true;
            columns["Element66"].IsVisible = true;
            columns["Element30"].IsVisible = true;
            columns["Element79"].IsVisible = true;
            columns["Element42"].IsVisible = true;
            columns["Element1"].IsVisible = true;
        }

        private void ScrollButton_OnClick(object sender, RoutedEventArgs e)
        {
            var column = grid.Columns["Element42"];
            grid.ScrollColumnIntoView(column);
        }
```

I hid all of the columns and then un-hid several random columns to approximate what I'm doing in my actual code.

As for the DataGridPage.xaml, all I did was add the `ScrollButton`.

Here's the zipped solution if it helps:
[UWPDataGridScrollTest.zip](https://github.com/telerik/UI-For-UWP/files/1560296/UWPDataGridScrollTest.zip)

**Comment by APopatanasov** [comment]
Hi @Nasawa ,

Thank you for the provided project.

Using it I was able to reproduce the described issue. It is caused by the the **ScrollColumnIntoView** method. Inside that method we try to get the index of the passed as a parameter column. However, we traverse the whole  Columns collection that contains both the Visible and Invisible columns. Because of that for your concrete scenario you are trying to scroll to column with index 42 (the index from the full collection) from a total number of 16 Visible columns - because of that IndexOutOfRangeException is thrown. In order to resolve the issue the method should be improved and more specifically the following line of code:
https://github.com/telerik/UI-For-UWP/blob/b420c29f3222ec6c34557d468b7787056a4750bc/Controls/Grid/Grid.UWP/View/RadDataGrid.Scrolling.cs#L113

The index should not be searched from the Columns collection but only from a collection that contains the visible columns.

Your workaround currently seems to be a nice one. Using the provided above information about the issue you could also try to work on this bug on your own and send us a pull request with the fix - I will be glad to review it.

Thank you for your collaboration. 😄
