### ISSUE TITLE
NumericEditor in RadDataGrid's external editor comes with default Maximum value of 100

### ISSUE THREAD

**Issue by WDev20** [telerik/UI-For-UWP#210]
Hi,

The following screenshot explains the bug with the NumericEditor for integer properties when its Maximum value is set to 100 by default.

![issue](https://user-images.githubusercontent.com/34504738/34269300-0e5fce6a-e684-11e7-91d5-79340ebafbbe.GIF)

Here's what the XAML editor shows in debug mode for the NumericEditor
![issue1](https://user-images.githubusercontent.com/34504738/34269451-a2f6504e-e684-11e7-8a32-0b94a0bb82d3.GIF)

**Comment by APopatanasov** [comment]
Hi @WDev20 ,

You are absolutely right. The NumericEditor is actually part of the the DataForm control that is used for editing the DataGrid when the edit mode is external. The Style of the NumericEditor control that is actually a child of the RadNumericBox has set Minimum and Maximum values to 0 and 100:
https://github.com/telerik/UI-For-UWP/blob/0d139af06e2a2d9cd87266faeeed03330aed5fc7/Controls/DataControls/DataControls.UWP/Themes/Generic.xaml#L274

You can either delete that xaml code and set it to the max and min int value in code-behind or replace the xaml with the max and min int values - the same is done for the RadNumericBox that is used when the mode is internal:
https://github.com/telerik/UI-For-UWP/blob/0d139af06e2a2d9cd87266faeeed03330aed5fc7/Controls/Grid/Grid.UWP/View/Columns/Resources/DefaultNumericalColumnEditorStyle.xaml#L12

Please, do not hesitate to make a pull request with either fix you preref - the one in code - behind or by changing the xaml. I will be glad to review it. 😄
