### ISSUE TITLE
COMException in RadRadialMenu

### ISSUE THREAD

**Issue by mscherotter** [telerik/UI-For-UWP#250]
Occasionally when opening and closing the RadRadialMenu, an unhandled exception is thrown - 
System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component. Here are the details from the debugger in VS 2017.  I still don't have a reliable repro.

   at Windows.UI.Xaml.UIElement.Measure(Size availableSize)
   at Telerik.UI.Xaml.Controls.Primitives.Menu.MenuItemLayer.ArrangeMenuItemControl(RadialSegment segmentModel)
   at Telerik.UI.Xaml.Controls.Primitives.Menu.MenuItemLayer.ShowVisual(RadialSegment segmentModel, Double startAngle)
   at Telerik.UI.Xaml.Controls.Primitives.Menu.RingModel.PrepareItem(RadialSegment menuItem)
   at T

**Comment by APopatanasov** [comment]
@mscherotter Several people have reported this issue. However, I have not been able to reproduce it on my side. I know it is really hard to be reproduced in a sample project however, I will appreciate isolating the issue if it is possible for you - or to provide some detailed steps how it could be reproduced. Without being able to reproduce the issue on my side it would be very hard for me to provide some information what might be the reason that is causing it.

I am looking forward to hearing from you.

**Comment by mscherotter** [comment]
I have been able to reproduce it by rapidly clicking and double-clicking on the central button – after a while, I get the crash.
Repro is here:
https://1drv.ms/f/s!AmvW0E0DYMdm3aZnh6FptnRTNVg63Q
Michael

**Comment by APopatanasov** [comment]
@mscherotter Thanks for the attached project. I was able to reproduce the exception. Unfortunately, after investigating it for a while I was not able to find what might be causing it. I apologize for not being able to provide some more detailed information. However, I really appreciate sending us the sample and the steps for reproducing it - they will be of great help once the issue is planned for fixing or when a member from the community desires to work on a fix.

**Comment by mscherotter** [comment]
Has the Telerik team looked at this anymore? - I can't use or recommend using the Radial menu control because of this bug.

**Comment by APopatanasov** [comment]
@mscherotter Currently, we don't have a solution for the observed issue. As mentioned in your previous response the issue occurs when the control is rapidly opened and closed. Because of that rapid clicking we cannot treat the issue with a high priority.

If you are interested in working on this issue please let me know and I will provide you some guidance that you can use as a starting point for the research and the fix.

**Comment by mscherotter** [comment]
The issue happens even when using normally, not rapidly.  The rapid clicking causes it sooner.

**Comment by APopatanasov** [comment]
@mscherotter For your convenience I have build the source for you and produced binaries you can use - please, check the attached file. 

Also, please be aware the provided binaries are not official one and I suggest you to use them only for test purposes.
[Binaries.zip](https://github.com/telerik/UI-For-UWP/files/2167379/Binaries.zip)

**Comment by mscherotter** [comment]
How should I include those binaries instead of the nuget ones?

**Comment by APopatanasov** [comment]
@mscherotter You need first to remove the installed nuget package. After that to right click on your project > Add Reference > Browse >_"Binaries Location"_> select the needed binaries >OK.

The binaries that are needed for the RadialMenu are **Telerik.Core.dll** and **Telerik.UI.Xaml.Primitves.dll.** I suggest you to add all dlls from the Binaries folder in case you are using some other controls and you are not exactly sure what binaries you need for them.

I hope this will help you to test the project.

**Comment by mscherotter** [comment]
Using the binaries you packaged I cannot reproduce the crash!
Thanks,
Michael

**Comment by APopatanasov** [comment]
I am glad to here the control is now working as expected and no exception is observed.

I will commit the fix into the development branch soon and it will be available with the next official release - it is scheduled for September.

I hope that this time frame is acceptable for you.

**Comment by mscherotter** [comment]
Any sooner would be fantastic as I can’t use the RadRadialMenu in its current state.
Thanks,
Michael

**Comment by APopatanasov** [comment]
You can also consider using the provided in my previous response binaries until the release of the official nuget package. Even though I have built the binaries for test purposes they should not deffer from the binaries we are building for the official releases and could be considered as stable.
