### ISSUE TITLE
DataGridDateColumn can't be set about CellEditorStyle property in < Style >

### ISSUE THREAD

**Issue by kanryu** [telerik/UI-For-UWP#260]
Hi,

I use < RadDataGrid > and < DataGridDateColumn  >, and I set CellEditorStyle in the usual way. The following XAML tags operate normally.

     <telerikGrid:DataGridDateColumn PropertyName="LimitYmd" Header="LimitDate" CellContentFormat="{}{0,0:yyyy/MM/dd}" SizeMode="Fixed" Width="120">
         <telerikGrid:DataGridDateColumn.CellEditorStyle>
             <Style TargetType="telerikInput:RadDatePicker">
                 <Setter Property="CalendarLanguage" Value="ja-JP"/>
                 <Setter Property="DisplayValueFormat" Value="yyyy/MM/dd"/>
                 <Setter Property="SelectorOrder" Value="ymd"/>
                 <Setter Property="SelectorHeader" Value="Select the Date"/>
             </Style>
         </telerikGrid:DataGridDateColumn.CellEditorStyle>
     </telerikGrid:DataGridDateColumn>

However, when Style is defined in Page.Resource, System.Runtime.InteropServices.COMException occurs. Specifically, the following error message is obtained.

_Cannot apply a Style with TargetType 'Telerik.UI.Xaml.Controls.Grid.DataGridDateColumn' to an object of type 'Windows.UI.Xaml.Controls.TextBlock'."_

    <Page.Resources>
        <Style TargetType="telerikGrid:DataGridDateColumn" x:Key="DateGridDateStyle">
            <Setter Property="CellEditorStyle">
                <Setter.Value>
                    <Style TargetType="telerikInput:RadDatePicker">
                        <Setter Property="CalendarLanguage" Value="ja-JP"/>
                        <Setter Property="DisplayValueFormat" Value="yyyy/MM/dd"/>
                        <Setter Property="SelectorOrder" Value="ymd"/>
                        <Setter Property="SelectorHeader" Value="Select the Date"/>
                    </Style>
                </Setter.Value>
            </Setter>
        </Style>
    </Page.Resources>
    
    <telerikGrid:DataGridDateColumn PropertyName="LimitYmd" Header="LimitDate" CellContentFormat="{}{0,0:yyyy/MM/dd}" SizeMode="Fixed" Width="120" CellContentStyle="{StaticResource DateGridDateStyle}" />

Comments?

**Comment by APopatanasov** [comment]
@kanryu The approach you are using for setting the Style is not accurate. The Style that targets the DatePicker control should be declared in the Resources section and after that just to be passed to the CellEditorStyle property of the DateGridDateColumn:
` <Page.Resources>
        <Style TargetType="input:RadDatePicker" x:Key="DatePickerStyle">
            <Setter Property="CalendarLanguage" Value="ja-JP"/>
            <Setter Property="DisplayValueFormat" Value="yyyy/MM/dd"/>
            <Setter Property="SelectorOrder" Value="ymd"/>
            <Setter Property="SelectorHeader" Value="Select the Date"/>
        </Style>
    </Page.Resources>`
and in the DataGrid:
`<telerikGrid:DataGridDateColumn PropertyName="NationalHoliday" Header="LimitDate" CellContentFormat="{}{0,0:yyyy/MM/dd}"
                                CellEditorStyle="{StaticResource DatePickerStyle}"/>`

I will proceed and close the issue. Please, also be aware that the UI for UWP team does not provide formal support, except to those customers who have purchased [a commercial license for UI for UWP](https://www.telerik.com/universal-windows-platform-ui). Please do not create support requests for this project in the issues list for this repo, as these will be immediately closed. You'll be directed to post your question on a community forum.

Hope the answer is helpful for you.

**Comment by kanryu** [comment]
Thanks you! :)
