### ISSUE TITLE
Implement and improve overall accessibility

### ISSUE THREAD

**Issue by timheuer** [telerik/UI-For-UWP#28]
The UI controls need to have better base implementations of accessibility patterns for users who rely on screen readers and other tools to interact with apps.  This item should track the overall improvement for each control:

- [x] DataForm
- [x] Grid
- [x] ListView
- [x] LoopingList
- [x] Calendar Scheduler
- [x] Date/Time Picker
- [x] Expander
- [x] AutoCompleteBox
- [x] NumericBox
- [x] Rating
- [x] RangeSlider
- [x] RadialMenu
- [x] HexView
- [x] SideDrawer
- [x] HubTile
- [x] Pagination
- [x] Charts
- [x] BusyIndicator
- [x] Map

**Comment by APopatanasov** [comment]
An accessibility has been implemented for all listed controls. The controls support:

- Keyboard support – focusing with Tab, depending on the control support for the Arrow keys, Home/End, PageUp/PageDown, Enter, Space etc.
- AutomationPeers for each control;
- HighContrast themes support – when the theme of the OS is changed to some of the provided HighContrast themes the controls are visualized according to the expectations of the chosen theme.

Any feedback about improving the current implementation of the accessibility is highly appreciated. 😊

**Comment by DhiMalo** [comment]
Just opened [Issue 457](https://github.com/telerik/UI-For-UWP/issues/457) regarding Accessibility, particularly for DataGrid which was not captured in the above checklist.
