### ISSUE TITLE
RadRating is not keyboard focusable/navigatable

### ISSUE THREAD

**Issue by timheuer** [telerik/UI-For-UWP#29]
When using the RadRating control, it doesn't grab keyboard focus when tabbed to.

**Comment by APopatanasov** [comment]
The issue has been resolved. Using the Tab key you could easily navigate between the RatingItems. As an addition we have have added a "FocusedStates" VisualStateGroup for visualizing an indicator which item is currently focused.
![2017-03-28_1620](https://cloud.githubusercontent.com/assets/9336157/24407392/6c9499a4-13d3-11e7-8d48-bcfe221adb6b.png)
Thank again for the report. 😄
