### ISSUE TITLE
DataGrid: "No installed components were detected" when i set DataGridNumericalColumn.HeaderStyle

### ISSUE THREAD

**Issue by DkmS1953** [telerik/UI-For-UWP#317]
Style is very simple:
<grid:DataGridNumericalColumn.HeaderStyle>
    <Style TargetType="TextBlock">
      _Setter Property="HorizontalAlignment" Value="Right" />
      _Setter Property="Padding" Value="0,0,3,0" />
    </Style>
</grid:DataGridNumericalColumn.HeaderStyle>

Error:

No installed components were detected.
Cannot apply a Style with TargetType 'Windows.UI.Xaml.Controls.TextBlock' to an object of type 'Telerik.UI.Xaml.Controls.Grid.Primitives.DataGridColumnHeader'.

**Comment by APopatanasov** [comment]
@DkmS1953 As the exception explains you are trying to apply Style that Targets type **TextBlock** to a visual element that is of type **DataGridColumnHeader**. **DataGridColumnHeader** is the visual element that gets visualized for the header part of the column and because of that the Style should target that type.

If you want to change the look of the TextBlock part of the Header you can simply set the following value as Header - the Header property is of type object and because of that any visual element could be set:
`<grid:DataGridNumericalColumn PropertyName="Value">
    <grid:DataGridNumericalColumn.Header>
        <TextBlock Text="{Binding PropertyName}" FontSize="18" Foreground="Red"/>
    </grid:DataGridNumericalColumn.Header>
</grid:DataGridNumericalColumn>`

Hope this helps.

**Comment by DkmS1953** [comment]
@APopatanasov 
Thanks for the reply. 
The recipe works, but only in part of the size and color of the font. The attempt to position the header text as I want is not successful. The text is always aligned to the left.
In the rows of the table, the alignment works as set in the style - right and indented from the edge.
`                                        <grid:DataGridNumericalColumn.Header>
                                            <TextBlock 
                                                Text="{Binding PropertyName}" Padding="0,0,3,0" HorizontalAlignment="Right" />
                                        </grid:DataGridNumericalColumn.Header>
                                        <grid:DataGridNumericalColumn.CellContentStyle>
                                            <Style TargetType="TextBlock">
                                                <Setter Property="HorizontalAlignment" Value="Right" />
                                                <Setter Property="VerticalAlignment" Value="Center" />
                                                <Setter Property="Padding" Value="0,0,3,0" />
                                            </Style>
                                        </grid:DataGridNumericalColumn.CellContentStyle>
`

**Comment by APopatanasov** [comment]
@DkmS1953 You can align it as desired by setting HorizontalContentAlignment to Center for the DataGridColumnHeader using the HeaderStyle:
`<grid:DataGridNumericalColumn PropertyName="Value">
                    <grid:DataGridNumericalColumn.Header>
                        <TextBlock Text="{Binding PropertyName}" FontSize="18" Foreground="Red"/>
                    </grid:DataGridNumericalColumn.Header>
                    <grid:DataGridNumericalColumn.HeaderStyle>
                        <Style TargetType="primitives:DataGridColumnHeader">
                            <Setter Property="HorizontalContentAlignment" Value="Center"/>
                        </Style>
                    </grid:DataGridNumericalColumn.HeaderStyle>
                </grid:DataGridNumericalColumn>`
