### ISSUE TITLE
RadNumericbox rejects decimal input on one some computers

### ISSUE THREAD

**Issue by JasperE84** [telerik/UI-For-UWP#332]
On some computers I'm having an issue where a radnumericbox won't accept decimal input. The same inputbox in the same app works fine with decimal input on all other on the network.

The problem is that when I'm entering a decimal sign, the textbox is immediately cleared of its value.

I wrote a debug app to register the VirtualKey number of the decimal and comma button. The VirtualKey value for the decimal and comma button on the keyboard is identical to the other computers where everything is working fine. Also win10 regional settings are equal between a computer with the issue and the others. (, = 188 and Decimal button = 110). Also the value of CurrentCulture.NumberFormat.NumberDecimalSeparator is "," on both the problematic and on the other workstations.

I also tried hooking up another keyboard which is working on another computer and rebooted the a problematic workstation. Still to no avail.

What could be the issue here? Any ideas?

Edit: It seems like this issue might be related to Win 10 1809 update. After some testing workstations on 1809 seem affected where as Win10 1803 are not.

**Comment by JasperE84** [comment]
It seems like computers running Win 10 1809 are affected where as Win10 1803 are not.

**Comment by APopatanasov** [comment]
Hi @JasperE84 ,

Thank you for the provided details. I will need some more time to investigate the issue. Once I have some more information I will let you know.

**Comment by JasperE84** [comment]
Thanks for the fix!
