### ISSUE TITLE
Navigating from child menu to top level in RadRadialMenu?

### ISSUE THREAD

**Issue by mscherotter** [telerik/UI-For-UWP#338]
From a command executed in a RadialMenuItem, how do I navigate back to the top-level menu?

If I call this

` var navigateContext = new NavigateContext(null);           RadialMenu.CommandService.ExecuteDefaultCommand(Telerik.UI.Xaml.Controls.Primitives.Menu.Commands.CommandId.NavigateToView, navigateContext);`

the navigation happens but the icon is the still the back button, not the gear button and pressing it goes back to the child menu.. I want the navigation popped from the navigation stack.

**Comment by APopatanasov** [comment]
Hi @mscherotter ,

From the provided description of your scenario it seems you are actually looking for a "NavigateBack" command. I have created such a command and you can find it on the following branch: https://github.com/telerik/UI-For-UWP/tree/Nasko/radial-navigateback

You can clone the branch and build the controls on your side, so you can test the command: `RadialMenu.CommandService.ExecuteDefaultCommand(Telerik.UI.Xaml.Controls.Primitives.Menu.Commands.CommandId.NavigateBack, null);`

If the command works for you I will merge it in the development branch and it will be available with the next nuget package.

I am looking forward to hearing from you.

**Comment by mscherotter** [comment]
That looks like it would work.

**Comment by APopatanasov** [comment]
There is a PR (#340) that is in a hold position. Once you confirm the command works for your I will merge the request. 😄

**Comment by mscherotter** [comment]
Do you have a sample app that demonstrates the behavior?

**Comment by APopatanasov** [comment]
Attach you can find a test project that contains the modified binaries. Hope this helps.
[RadRadialMenu_338.zip](https://github.com/telerik/UI-For-UWP/files/2581447/RadRadialMenu_338.zip)

**Comment by mscherotter** [comment]
Perfect - that is exactly what was needed.  I approved the change.
