### ISSUE TITLE
Add sample app

### ISSUE THREAD

**Issue by lukasf** [telerik/UI-For-UWP#35]
A sample app should be included here, which shows all the available UWP controls and their most important functions. That way, users can play with the controls to find out how they work.

**Comment by stefanov-stefan** [comment]
Its coming up really soon @lukasf . Stay tuned.

**Comment by lukasf** [comment]
@stefanov-stefan Cool, looking forward to it!

**Comment by APopatanasov** [comment]
@lukasf a sample application that demonstrates the controls in action has been added to the repository. I hope you will like them. 😄

**Comment by lukasf** [comment]
Thank you @APopatanasov, I will definitely check it out!
