### ISSUE TITLE
Column Resize Event 

### ISSUE THREAD

**Issue by didi2391** [telerik/UI-For-UWP#358]
Whenever I resize any column within the grid is there an event where I can subscribe and get the actual width of the resized columns to be stored somewhere similar to ColumnCollectionChanged Event

**Comment by APopatanasov** [comment]
@didi2391 There isn't any event exposed by the control or the column that gets thrown when the column is resized. However, you can easily get the desired information by finding the DataGridColumnHeader visual elements that hold the column header itself and subscribe to the SizeChanged event.

Please, check the attached project that demonstrates that.
[App13.zip](https://github.com/telerik/UI-For-UWP/files/2758632/App13.zip)

Hope this helps.
