### ISSUE TITLE
RadDataGrid - Nested DataGrid support - 4 Level

### ISSUE THREAD

**Issue by didi2391** [telerik/UI-For-UWP#368]
Scenario : I need to support 3 levels of Nested Data Grid

Approach: 

1) . 1st level (Parent Grid) I am auto generating columns through Properties which works fine

2) . On Selection Change in Parent Grid , I am setting one of the dynamic property(Collection) of the Parent Grid to the 2nd level Data grid and showing the row details template and works fine

I have given the x:name property on both 2nd and 3rd level grid inside the template but it is inaccessible since It is put up inside the data template because of which I am unable to successfully nest the third level grid 

I am also using "Generate Column Command" to handle the Column Auto generation process works for 2 levels

https://docs.telerik.com/devtools/universal-windows-platform/controls/raddatagrid/features/commands/datagrid-generatecolumncommand

Can I have an example that shows nesting upto 3 or 4 levels of Rad Data Grid so that to see where I am missing

**Comment by didi2391** [comment]
Figured it out myself 

Selection changed was calling multiple times which was causing the inner grid not to show the templates as it was getting reset

**Comment by APopatanasov** [comment]
I am glad to here you were able to find a suitable solution for your scenario. The issue will be closed as requested.
