### ISSUE TITLE
Extend DataGrid Selection Mode to support ctrl and shift selections

### ISSUE THREAD

**Issue by gatchmart** [telerik/UI-For-UWP#369]
## Summary
I would like to add the ability for someone to select multiple or extended SelectionModes. Where extended you would select rows/cells using the ctrl and shift keys.

## API Changes

In order support the Extended option I would add Extended to the DataGridSelectionMode enum:
```
 public enum DataGridSelectionMode
    {
        /// <summary>
        /// No selection is allowed.
        /// </summary>
        None,

        /// <summary>
        /// Single unit only may be selected. The selection unit is described by the <see cref="RadDataGrid.SelectionUnit"/> property.
        /// </summary>
        Single,

        /// <summary>
        /// Multiple units may be selected. The selection unit is described by the <see cref="RadDataGrid.SelectionUnit"/> property.
        /// </summary>
        Multiple,

        /// <summary>
        /// Items are added to the selection only by combining the mouse clicks with the Ctrl or Shift keys. The selection unit is described by the <see cref="RadDataGrid.SelectionUnit"/> property.
        /// </summary>
        Extended // new API
    } 
```

Due to this modification I would have to modify the follow functions of the SelectionService class:

### SelectionService constructor:
```
// Change from this:
this.selectedItems.AllowMultipleSelect = this.Owner.SelectionMode == DataGridSelectionMode.Multiple;

// To this:
this.selectedItems.AllowMultipleSelect = ( this.Owner.SelectionMode == DataGridSelectionMode.Multiple || this.Owner.SelectionMode == DataGridSelectionMode.Extended );
```

### OnSelectionModeChanged:
```
// Change from this:
if (dataGridSelectionMode == DataGridSelectionMode.Multiple)
{
    this.ClearSelection();
}

this.selectedItems.AllowMultipleSelect = dataGridSelectionMode == DataGridSelectionMode.Multiple;

// To this:
if (dataGridSelectionMode == DataGridSelectionMode.Single || dataGridSelectionMode == DataGridSelectionMode.None)
{
    this.ClearSelection();
}

this.selectedItems.AllowMultipleSelect = ( dataGridSelectionMode == DataGridSelectionMode.Multiple ||  dataGridSelectionMode == DataGridSelectionMode.Extended );
```

### SelectAll:
```
// Change from this:
if (this.SelectionMode != DataGridSelectionMode.Multiple)
{
    return;
}

// To this:
if (this.SelectionMode == DataGridSelectionMode.Single || this.SelectionMode == DataGridSelectionMode.None)
{
    return;
}
```

### SelectCellUnit:
```
// Change from this:
switch (this.Owner.SelectionMode)
{
   case DataGridSelectionMode.Single:
       this.SelectSingleCellUnit(cellInfo, select);
       break;
   case DataGridSelectionMode.Multiple:
       this.SelectMultipleCellUnits(cellInfo, select, uiSelect);
       break;
   default:
       break;
}

// To this:
if ( this.Owner.SelectionMode == DataGridSelectionMode.Single )
{
    this.SelectSingleCellUnit(cellInfo, select);
}
else if (this.Owner.SelectionMode == DataGridSelectionMode.Multiple || this.Owner.SelectionMode == DataGridSelectionMode.Extended)
{
    this.SelectMultipleCellUnits(cellInfo, select, uiSelect);
}
```

### SelectRowUnit:
```
// Change from this:
switch (this.Owner.SelectionMode)
{
    case DataGridSelectionMode.Single:
        this.SelectSingleRowUnit(rowItem, select);
        break;
    case DataGridSelectionMode.Multiple:
        this.SelectMultipleRowUnits(rowItem, select, toggleSelection);
        break;
    default:
        break;
}

// To this:
if ( this.Owner.SelectionMode == DataGridSelectionMode.Single )
{
    this.SelectSingleRowUnit(rowItem, select);
} 
else if ( this.Owner.SelectionMode == DataGridSelectionMode.Multiple || this.Owner.SelectionMode == DataGridSelectionMode.Extended )
{
    this.SelectMultipleRowUnits(rowItem, select, toggleSelection);
}
```
All of these changes add support for the addition of the DataGridSelectionMode.Extended option.

---

I will add the following varible to the RadDataGrid.Selection.cs file:
`internal DataGridCellInfo previousSelectedCell;`
This provides a means of tracking the previously selected cell to be used with the shift click selection.

---
The following modifications would be made to the RadDataGrid.Manipulation.cs file

### OnCellTap:
```
// Change from this:
this.selectionService.Select(cellInfo.Cell);

// To this:
if ( this.SelectionMode == DataGridSelectionMode.Single || this.SelectionMode == DataGridSelectionMode.Multiple )
{
    this.selectionService.Select(cellInfo.Cell);
}
else if ( this.SelectionMode == DataGridSelectionMode.Extended )
{
    // Check if ctrl or shift is pressed, if one of them is execute it accordingly
    if ( KeyboardHelper.IsModifierKeyDown( VirtualKey.Shift ) )
    {
        if ( this.previousSelectedCell != null )
        {
            for ( int index = this.previousSelectedCell.RowItemInfo.Slot+1; index < cellInfo.RowItemInfo.Slot; index++ )
            {
                var cell = this.Model.CellsController.GetCellsForRow(index).FirstOrDefault();
                if (cell != null)
                {
                    this.selectionService.Select( cell );
                }
            }
            
            this.selectionService.Select(cellInfo.Cell);
            previousSelectedCell = cellInfo;
        }
    }
    else if ( KeyboardHelper.IsModifierKeyDown( VirtualKey.Control ) )
    {
        this.previousSelectedCell = cellInfo;
        this.selectionService.Select(cellInfo.Cell);
    }
    else
    {
        this.selectionService.ClearSelection();
        this.previousSelectedCell = cellInfo;
        this.selectionService.Select(cellInfo.Cell);
    }
}

```

### HandleKeyDown:
```
// This code will be added to support Selecting all cells with ctrl+a
case VirtualKey.A:
	if ( KeyboardHelper.IsModifierKeyDown( VirtualKey.Control ) && this.SelectionMode == DataGridSelectionMode.Extended)
	{
	    this.selectionService.SelectAll();
	}
	break;
```
This code is the meat and potatoes of the new selection mode. It allows correct selection to using the ctrl and shift keys. Holding ctrl and clicking will allow a user to select random cells not in a row. Holding shift and clicking will select all rows from the previously selected cell to the newly selected cell.

## Intended Use Case
The addition of an extended selection mode will allow developers of large data sets to provide a fast means for their users to select large amounts of data. With the current selection mode, a user selecting 10 rows would have to select each row individually. With the Extended selection mode a user would only has to select the first and last rows to select all 10 rows. This is not a massive change to the API but one that helps provide users with the selection funcationallity they are used to in Windows.

To use this new selection mode a developer only needs to change the RadDataGrid's SelectionMode from Multiple to Extended.

**Comment by APopatanasov** [comment]
Hi @gatchmart ,

Adding an extended selection to the DataGrid control is absolutely legit feature request. From the provided detailed information it seems you are on the right path how the feature could be implemented.

If you are interested in working on this feature feel free to ask me questions if you have any and I will be glad to review your pull request.

**Comment by gatchmart** [comment]
@APopatanasov I definitely interested in working on this feature. The code I provided gets the feature to work but I will need to do additional testing to set how it performs when a user only wants to select cells as opposed selecting rows. Do you see anything that you would like changed or any obvious issues with the provided code?

**Comment by APopatanasov** [comment]
@gatchmart I have a few minor comments about the code, but I believe this is only the initial start of the full implementation of the extended selection of the DataGrid. You are on the right path where the feature should be implemented in the code, but it needs to cover the following scenarios:

**Row Extended Selection:**
- If there is no selection in the DataGrid. Pressing Shift + Mouse click should select from the first row to the row you have been clicked:

 ![1](https://user-images.githubusercontent.com/9336157/51683027-917d5400-1ff1-11e9-9c29-4cf7e0281697.gif)

- DataGrid with selected row and Shift + Mouse click. A selection should be made from to the selected row to the clicked row.

![2](https://user-images.githubusercontent.com/9336157/51683049-9e9a4300-1ff1-11e9-9e2a-00a6c92c9a1e.gif)

- Ctrl + Mouse click should select/deselect the row

![3](https://user-images.githubusercontent.com/9336157/51683062-a5c15100-1ff1-11e9-8950-f262f997d0ef.gif)

**Cell Extended Selection:**

- If there is no selection in the DataGrid. Pressing Shift + Mouse click on a cell should select from the first cell of the first row to the cell you have been clicked:

![4](https://user-images.githubusercontent.com/9336157/51683079-abb73200-1ff1-11e9-89e7-7e2f415ea57c.gif)

- DataGrid with selected cell and Shift + Mouse click. A selection should be made from to the selected cell to the clicked cell.

![7](https://user-images.githubusercontent.com/9336157/51683257-18323100-1ff2-11e9-94cb-577359333273.gif)

- Ctrl + Mouse click should select/deselect the cell.

![6](https://user-images.githubusercontent.com/9336157/51683095-b5d93080-1ff1-11e9-9603-5642dac033f7.gif)

- Select with Shift + Mouse click. Press Ctrl + mouse click. Select again with Shift + Mouse click. It should behave like this.

![8](https://user-images.githubusercontent.com/9336157/51683591-de155f00-1ff2-11e9-9569-14b5b22e4f31.gif)

I hope the provided information will be helpful for you. 

If you have any additional questions please, let me know.
