### ISSUE TITLE
RadDataGrid throws a layout cycle exception 

### ISSUE THREAD

**Issue by KarlErickson** [telerik/UI-For-UWP#38]
See https://github.com/Microsoft/Windows-appsample-customers-orders-database/issues/3

This appears to be an issue with the RadDataGrid control and not the sample code because we can reproduce it in a new app with just the control, as long as the control is the right size and has the right contents. For a simplified repro, see https://github.com/KarlErickson/layout-cycle. The exception occurs consistently on launch with this repro, but only on some of the machines we tested it on. We couldn't repro on most machines we tried it on.

**Comment by APopatanasov** [comment]
Hi @KarlErickson ,
Apologize for the delayed reply. Could you please, share with the us the size of the DataGrid and the content it needs, so we could be able to reproduce the issue on our side? An additional information like inside what Panel the control is placed in will also be helpful.

**Comment by pkoecker** [comment]
I am facing a similar issue. 

We cannot reproduce the issue on our machines. It only appears until now on Microsoft Surface Books with Windows 10.0.15063.296. 

Exception:
Windows.UI.Xaml.LayoutCycleException - Layout cycle detected.  Layout could not complete.
System.AggregateException - A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Value does not fall within the expected range.)

Here is the Code for the Grid:

`   <telerikGrid:RadDataGrid Name="ProductsGrid"
                                 Grid.Row="1"
                                 MaxHeight="500"
                                 Margin="0 12 0 0"
                                 AutoGenerateColumns="False"
                                 GridLinesBrush="{ThemeResource BorderBrush}"
                                 GridLinesVisibility="Horizontal"
                                 IncrementalLoadingMode="Auto"
                                 IsBusyIndicatorEnabled="True"
                                 IsSynchronizedWithCurrentItem="True"
                                 ItemsSource="{x:Bind ViewModel.Products, Mode=OneWay}"
                                 UserGroupMode="Disabled">
            <telerikGrid:RadDataGrid.Columns>
                <telerikGrid:DataGridTemplateColumn Width="50" SizeMode="Fixed">
                    <telerikGrid:DataGridTemplateColumn.CellContentTemplate>
                        <DataTemplate>
                            <Grid>
                                <CheckBox Width="36"
                                          MinWidth="36"
                                          HorizontalAlignment="Center"
                                          VerticalAlignment="Center"
                                          Click="CheckBox_Click"
                                          IsChecked="{Binding Selected,
                                                              Mode=OneWay}" />
                            </Grid>
                        </DataTemplate>
                    </telerikGrid:DataGridTemplateColumn.CellContentTemplate>
                </telerikGrid:DataGridTemplateColumn>
                <telerikGrid:DataGridTextColumn x:Uid="ProductId" PropertyName="ProductId" />
                <telerikGrid:DataGridTextColumn x:Uid="ProductFamily" PropertyName="ProductFamily" />
                <telerikGrid:DataGridTextColumn x:Uid="Name" PropertyName="Name" />
            </telerikGrid:RadDataGrid.Columns>
        </telerikGrid:RadDataGrid>`

**Comment by APopatanasov** [comment]
Hi @pkoecker ,

We have tested the described scenario on a machine with Windows 10.0.15063.29, but we were not able to reproduce the issue.  Attached bellow is the sample we used for our test purposes. Could you please let us know if we are missing something and modify the project in order to be able to reproduce it on our side?
[App4.zip](https://github.com/telerik/UI-For-UWP/files/1037494/App4.zip)

**Comment by pkoecker** [comment]
Hi @APopatanasov ,

I have tested the project you provided and experimented with it, but I was unable to reproduce the issue on my machine. I am trying to contact some of our customers with Microsoft Books and try it on their machines as well. I will report back, if I have any results

**Comment by APopatanasov** [comment]
@pkoecker When you have an additional information for us, please let us know. 😊
