### ISSUE TITLE
Unable to write 6 with an azerty keyboard

### ISSUE THREAD

**Issue by Gimgur** [telerik/UI-For-UWP#380]
### Steps to Reproduce

1. have your computer un french culture with azerty keyboard
2. Tape capslock 6 in a numeric field
3. 

### Expected Behavior
A 6 is written
### Actual Behavior
The signe minus (-) is entered
### Basic Information
The error is in the file RadNumericBox.cs in the function private static bool IsNumericKey(VirtualKey key)

if (RadNumericBox.IsAzertyKeyboard && key == VirtualKey.Number6 && DeviceTypeHelper.GetDeviceType() != DeviceType.Phone)
            {
                return false;
            }

            if (key >= VirtualKey.Number0 && key <= VirtualKey.Number9)
            {
                return true;
            }

Should be

            if (key >= VirtualKey.Number0 && key <= VirtualKey.Number9)
            {
                return true;
            }

            if (RadNumericBox.IsAzertyKeyboard && key == VirtualKey.Subtract && DeviceTypeHelper.GetDeviceType() != DeviceType.Phone)
            {
                return false;
            }

- Version with issue:
- Last known good version:
- IDE:
- UWP SDK:   
- Nuget Packages:

**Comment by APopatanasov** [comment]
Hi @Gimgur ,

I have checked the code in the "IsNumericKey" method and I believe it can be improved as well. In the azerty keyboard pressing "6" is actually the sign "-". However, as you have already mentioned when CapsLock is pressed (or the Shift) the number should not be treated like minus sign. 

I have applied a fix #381 for this particular case. So, basically when either CapsLock or Shift is pressed the number should be entered as expected. 

If you have any additional questions or concerns about the fix please, let me know.
