### ISSUE TITLE
RadAutoCompleteBox: Ability to not select all when it receives the focus

### ISSUE THREAD

**Issue by blakepell** [telerik/UI-For-UWP#386]
## Summary
Provide a property/DependencyProperty that would allow the RadAutoCompleteBox to not select all the text in the underlying TextBox when it receives the focus.  The default behavior however would continue to stay as it functions today as to not break backwards compatibility.

## API Changes

A bool DependencyProperty/Property would be added to indicate whether the text in the underlying text box should be selected when it receives the focus.

This would look something like:

```
/// <summary>
/// Identifies the <see cref="SelectAllOnFocus"/> dependency property.
/// </summary>
public static readonly DependencyProperty SelectAllOnFocusProperty =
    DependencyProperty.Register(nameof(SelectAllOnFocus), typeof(bool), typeof(RadAutoCompleteBox), new PropertyMetadata(true));

/// <summary>
/// Gets or sets a value indicating whether the control should select all of the text when it gets the focus.
/// </summary>
public bool SelectAllOnFocus
{
    get
    {
        return (bool)this.GetValue(SelectAllOnFocusProperty);
    }
    set
    {
        this.SetValue(SelectAllOnFocusProperty, value);
    }
}
```

The `OnTextBoxGotFocus` method would then be updated to reference the above bool to determine whether it should select the text (which is done through the `UpdateCaretPosition()` method.

```
if (this.SelectAllOnFocus)
{
    this.UpdateCaretPosition();
}

```

## Intended Use Case

The intended use case would be when another control sets the focus to the RadAutoCompleteBox but does not want all of the text selected.

My specific use case is when a user starts typing anywhere in the program window and the key is intercepted and sent to the RadAutoCompleteBox as if it were typed there and then the focus is set to the RadAutoCompletebox so typing can continue there seamlessly.  If the text is automatically all selected on focus the result is the key is sent there and the next key press deletes the text that was selected.  In my case, there is one input text box on the window (the RadAutoCompleteBox) so key presses from anywhere else on the page are re-routed to the that control with the expectation that they can continue typing.

I would be happy to fill out contribution agreement and issue a pull request if this was deemed a valuable and sound contribution.

**Comment by APopatanasov** [comment]
Hi @blakepell,

I like the idea of having such property in the AutoCompleteBox control. Feel free to fill the [CLA](https://docs.google.com/forms/d/e/1FAIpQLSfQAzVxnnfwRQmtJCVmB41_ig1gYow--Gr8qLvaDxJRNHPtUQ/viewform) and to submit a PR. I will be glad to review it.
