### ISSUE TITLE
entry data to datagrid

### ISSUE THREAD

**Issue by khoshroomahdi** [telerik/UI-For-UWP#414]
## Summary
actually, I couldn't find how to enter data to Datagrid.ex: I want to copy data from excel sheet and past to Datagrid.

**Comment by APopatanasov** [comment]
Currently, the DataGrid control does not provide pasting from excel or another external data source out of the box. You can however, achieve a very similar to the desired functionality using the following example from MSDN: https://code.msdn.microsoft.com/windowsapps/Clipboard-App-sample-309ec122

I have also created a sample project that demonstrates the described in the article approach.

Hope this helps.
[RadDataGrid_414.zip](https://github.com/telerik/UI-For-UWP/files/3540677/RadDataGrid_414.zip)

**Comment by khoshroomahdi** [comment]
not like this

**Comment by khoshroomahdi** [comment]
how to make datagrid empty?

**Comment by APopatanasov** [comment]
If the ItemsSource of the DataGrid is bound to a collection that is INotityCollectionChange (like ObservableCollection) changes of that collection will automatically be visualized in the DataGrid as well. So if the collection is empty the DataGrid will be empty as well.

Please, also be aware that the UI for UWP team does not provide formal support, except to those customers who have purchased [a commercial license for UI for UWP](https://www.telerik.com/universal-windows-platform-ui). Please do not create support requests for this project in the issues list for this repo, as these will be immediately closed.
