### ISSUE TITLE
Unable to install multi-platform bundle that includes Telerik.UI.for.UniversalWindowsPlatform

### ISSUE THREAD

**Issue by Zofware** [telerik/UI-For-UWP#441]
### Description
Any app that includes Telerik.UI.for.UniversalWindowsPlatform cannot be installed successfully if built as a multi-platform bundle. For example, if I start with the default blank UWP app in Visual Studio 2019, add Telerik.UI.for.UniversalWindowsPlatform to it, then build a bundle for x64 and ARM64 the install fails with the following error:

`App installation failed with error message: Merge failure for shared merged PRI file : error 0x80070490 : Cannot register the ffed6aa4-df6d-476c-b790-31d891bae046_1.0.0.0_x64__hz258y3tkez3a package because there was a merge failure with the following file: C:\Program Files\WindowsApps\ffed6aa4-df6d-476c-b790-31d891bae046_1.0.0.0_neutral_split.scale-180_hz258y3tkez3a\resources.pri (0x80070490)`

### Steps to Reproduce

1. Use Visual Studio 2019 to create a "Blank App (Universal Windows)".
2. Set the target platform version to "Windows 10, version 1903 (10.0; Build 18362)" and the minium version to "Windows 10; version 1809 (10.0; Build 17763)".
3. Use NuGet to add Telerik.UI.for.UniversalWindowsPlatform" to the project.
4. Create an app package for sideloading choosing "Generate app bundle: Always" and targeting "Release (x64)" and "Release (ARM64)".
5. Attempt to install the resulting msixbundle. It will fail with a "Merge failure for shared merged PRI file".

### Expected Behavior
App should install normally.

### Actual Behavior
App install fails with an error:
`App installation failed with error message: Merge failure for shared merged PRI file : error 0x80070490 : Cannot register the ffed6aa4-df6d-476c-b790-31d891bae046_1.0.0.0_x64__hz258y3tkez3a package because there was a merge failure with the following file: C:\Program Files\WindowsApps\ffed6aa4-df6d-476c-b790-31d891bae046_1.0.0.0_neutral_split.scale-180_hz258y3tkez3a\resources.pri (0x80070490)`

### Basic Information

- Version with issue: I used 1.0.1.8 but I've seen this other versions too.
- Last known good version: Unknown. I've been having this problem since I started trying to target ARM64 when the Surface Pro X was announced last autumn.
- IDE: Microsoft Visual Studio Community 2019  Version 16.4.4 but I've also had the same problem when using Visual Studio 2017
- UWP SDK: Target: Windows 10, version 1903 (10.0; Build 18362); Minimum: Windows 10; version 1809 (10.0; Build 17763)
- Nuget Packages: Telerik.UI.for.UniversalWindowsPlatform

### Screenshots
![Image1](https://user-images.githubusercontent.com/51502102/73964708-97c23380-48c7-11ea-82df-2d9aa5721a58.png)
![Image2](https://user-images.githubusercontent.com/51502102/73964716-9abd2400-48c7-11ea-9d09-79a8d18e295d.png)
![Image3](https://user-images.githubusercontent.com/51502102/73964722-9d1f7e00-48c7-11ea-9dee-fb60481128b4.png)
![Image4b](https://user-images.githubusercontent.com/51502102/73964731-a01a6e80-48c7-11ea-8a82-8de922127ac8.png)
![Image5](https://user-images.githubusercontent.com/51502102/73964734-a27cc880-48c7-11ea-8fc8-caa142a9936a.png)
![Image6](https://user-images.githubusercontent.com/51502102/73964737-a3adf580-48c7-11ea-8d47-ba1fbd849811.png)
![Image7](https://user-images.githubusercontent.com/51502102/73964739-a577b900-48c7-11ea-950f-2c3aeb964356.png)
![Image8](https://user-images.githubusercontent.com/51502102/73964748-a90b4000-48c7-11ea-8307-f6612b92bfce.png)
![Image9](https://user-images.githubusercontent.com/51502102/73964752-aa3c6d00-48c7-11ea-9cd2-c57416dc1a73.png)
![Image10](https://user-images.githubusercontent.com/51502102/73964758-ad375d80-48c7-11ea-9eef-8958409d8b15.png)

### Reproduction Link
Visual Studio project:
[App1.zip](https://github.com/telerik/UI-For-UWP/files/4166988/App1.zip)

**Comment by Zofware** [comment]
There does appear to be a workaround but I'm not sure it's a good idea because it disables splitting resource packages for different scale resources. Even with the workaround there's clearly a bug still lurking here but I don't know if it's in how the UI-For-UWP package is laid out or if it's a bug in the way Visual Studio builds packages containing a variety of resource scales.

FWIW, the workaround is to add the following to the first `PropertyGroup` in the .csproj project file:
```
<AppxBundleAutoResourcePackageQualifiers>Language|DXFeatureLevel</AppxBundleAutoResourcePackageQualifiers>
```

I got the idea for this workaround from this page:
https://docs.microsoft.com/en-us/windows/uwp/app-resources/build-resources-into-app-package

**Comment by APopatanasov** [comment]
Hi @Zofware ,

Almost every control that is part of the nuget package is build in AnyCPU configuration. The only exception is the Map control that is separately built for x86, x64 and ARM - there isn't an ARM64 configuration. 

One of the reasons for the observed by you issue might be the fact that the Map control doesn't have an ARM64 build binaries. Unfortunately, currently we don't have an ARM64 device to test that theory. Attached you can find a nuget package that doesn't include the Map inside it. Could you please, test your solution using the provided nuget and let me know if the issues still occurs.

Thanks in advance.

I am looking forward to hearing from you. 
[Telerik.UI.for.UniversalWindowsPlatform.1.0.1.8.zip](https://github.com/telerik/UI-For-UWP/files/4180320/Telerik.UI.for.UniversalWindowsPlatform.1.0.1.8.zip)

**Comment by Zofware** [comment]
Yes! That was it. My test app when built with the map-less nuget package you provided installs successfully. I don't use the map control so this map-less version of your nuget package seems like a viable solution to my problem. Would you consider publishing a map-less version of your package to nuget going forward (or add an ARM64 configuration to your current package)?

I'm in the same boat as you as far as not having an ARM64 device to test with. I live just a few minutes from a Microsoft Store which has several Surface Pro X devices on hand. The employees there have been willing to let me run tests on their devices in the past (as long as it's something I can install from the online Store). My plan is to build an ARM64 test app and publish it to the online Store then drive over to the physical Store to test it. If you want to build and publish a ARM64 test app for any of your stuff I'm happy to test it at the physical Microsoft Store and give you a report.

**Comment by APopatanasov** [comment]
@Zofware thanks for the confirmation that the nuget works without the Map control. I have added the ARM64 build architecture for the Map and build a new package that includes it.

When you have an opportunity can you please test it and let me know if it works.

Thanks again for your help.
[Telerik.UI.for.UniversalWindowsPlatform.1.0.1.8.zip](https://github.com/telerik/UI-For-UWP/files/4186352/Telerik.UI.for.UniversalWindowsPlatform.1.0.1.8.zip)

**Comment by Zofware** [comment]
@APopatanasov unfortunately no luck with this one. When I build for x64 and ARM64 and try to install on x64 I get the following error:

`App installation failed with error message: Merge failure for shared merged PRI file : error 0x80070490 : Cannot register the ffed6aa4-df6d-476c-b790-31d891bae046_1.0.6.0_x64__hz258y3tkez3a package because there was a merge failure with the following file: C:\Program Files\WindowsApps\ffed6aa4-df6d-476c-b790-31d891bae046_1.0.6.0_neutral_split.scale-180_hz258y3tkez3a\resources.pri (0x80070490)`

When I build for x64 and ARM (not ARM64) then it installs on x64 successfully. Very strange. There's definitely something fishy with the ARM64 configuration. I have to wonder if it's something with the assets/resources rather than the binary because the error message mentions the resources file.

**Comment by APopatanasov** [comment]
@Zofware I think I was able to fix the ARM64 configuration - I have missed to enable the native toolchain when building for Release ARM64. I am no longer able to observe any issues when building a package for x64 and ARM64 - I have tested on machines with x64 architecture.

Attached you can find a nuget package that contains the latest changes. Could you please, test you application again?
[Telerik.UI.for.UniversalWindowsPlatform.1.0.1.9.zip](https://github.com/telerik/UI-For-UWP/files/4193216/Telerik.UI.for.UniversalWindowsPlatform.1.0.1.9.zip)

**Comment by Zofware** [comment]
I think you can declare victory. That worked for me building for x64+ARM64 and installing on x64. Thank you!

**Comment by APopatanasov** [comment]
@Zofware Thanks for your confirmation that now everything works as expected.  

I will make a pull request with the changes that add the ARM64 configuration for the Map control. Once the request is merged the fix will be available with the next official nuget release scheduled for May. 

In the meantime you can use the package provided in my latest response.

Thank you again for your collaboration.

**Comment by Zofware** [comment]
Thanks Atanas!

**Comment by Zofware** [comment]
@APopatanasov here is the Telerik DataGrid running in an ARM64 UWP app on a Surface Pro X using the 1.9 build you linked above. I didn't test the map control though, but at least I can confirm the data grid works on ARM64. Thanks again.

![image](https://user-images.githubusercontent.com/51502102/75485774-27f01780-5960-11ea-90c5-c16d8a3a5045.png)
