### ISSUE TITLE
Wrong drawing chart series

### ISSUE THREAD

**Issue by Wufus** [telerik/UI-For-UWP#442]
### Description
When series VerticalAxis have setted maximum less than some of datapoints value or VerticalAxis have setted minimum more than some of datapoints value, the series will drawn incorrectly.
With some types of series value drawing not properly:
- LineSeries
- AreaSeries
- SplineSeries
- SplineAreaSeries
- StepLineSeries
- StepAreaSeries

### Steps to Reproduce

1. I upload simple solution for reproduce https://github.com/Wufus/Test-Telerik
2. Build & run
3. Click "Set min=4 max=8" button -> series draw incorrectly (some data points skipped)
4. Click "Zoom + offset" button -> series draw correctly (no data points skipped)

### Expected Behavior
With setting manual minimum or maximum , the line must be
![Good](https://user-images.githubusercontent.com/41466857/74099225-53869b80-4b32-11ea-86f1-26b257a819c8.jpg)
In this screenshot i set zoom and offset, for imitate maximum 8 and minimum 4.
The line drawing good.

### Actual Behavior
But i see
![Bad](https://user-images.githubusercontent.com/41466857/74099212-3225af80-4b32-11ea-9975-a87c5667ee1a.jpg)
Data points at X = 4, 6, 8 -11 are skipped

### Basic Information

- Version with issue: 
- Last known good version: -
- IDE: Visual Studio 2019 16.4
- UWP SDK: 18362
- Nuget Packages: 1.0.1.4 - 1.0.1.8

**Comment by APopatanasov** [comment]
Hi @Wufus ,

Thank you for the provided project. Using it I was able to easily reproduce the described issue. 

As the issues is target with hight priority I am glad to inform you that I have already made a fix about it. Once it gets merged in the development branch it will be available with the next official nuget package scheduled for May.

If you want to get the fix asap you can build a nuget from the development branch by yourself. A detailed information how a custom nuget can be built you can find [here](https://github.com/telerik/UI-For-UWP/wiki/How-to-Build-UI-For-UWP-NuGet).

**Comment by Wufus** [comment]
Perfectly!
![Done](https://user-images.githubusercontent.com/41466857/74309178-2b3dad80-4d7b-11ea-9102-7a33bee75dbc.png)
