### ISSUE TITLE
Change Size of Busy Indicator?

### ISSUE THREAD

**Issue by seanocali** [telerik/UI-For-UWP#449]
I don't seem to be able to do this. Even in the template.

**Comment by APopatanasov** [comment]
Hi @seanocali ,

All built-in animations of the BusyIndicator have a specific size that cannot be changed. If you want to make the indicator bigger you need to create a custom animation as described in the following link from the documentation:
[https://docs.telerik.com/devtools/universal-windows-platform/controls/radbusyindicator/busyindicator-customanimations](https://docs.telerik.com/devtools/universal-windows-platform/controls/radbusyindicator/busyindicator-customanimations)

By defining a style of your own you can set any desired size. If you want to reuse some of the default Styles you can found them [here](https://github.com/telerik/UI-For-UWP/tree/development/Controls/Primitives/Primitives.UWP/BusyIndicator/Animations) - simply copy/paste them and change the sizes as desire.

I have created a sample project that demonstrates how to achieve this - please, check it.

Please, also be aware that the UI for UWP team does not provide formal support, except to those customers who have purchased [a commercial license for UI for UWP](https://www.telerik.com/universal-windows-platform-ui). Please do not create support requests for this project in the issues list for this repository, as these will be immediately closed.

Hope this helps.
[RadBusyIndicatorUWP_449.zip](https://github.com/telerik/UI-For-UWP/files/4260639/RadBusyIndicatorUWP_449.zip)
