### ISSUE TITLE
Ship nuget pkg

### ISSUE THREAD

**Issue by bc3tech** [telerik/UI-For-UWP#45]
What's the reason for not simply publishing UI-for-UWP as a nuget package but instead make everybody clone the repo and build it themselves?

Please ship the current state as a nuget pkg on a regular cadence.

**Comment by stefanov-stefan** [comment]
Hi @bc3tech, Nuget is available already, you can get it here: https://www.nuget.org/packages/Telerik.UI.for.UniversalWindowsPlatform/

**Comment by bc3tech** [comment]
Thank you. We should link this in press material and docs instead of only pointing to the repo...

I searched "Telerik UWP" and that package didn't pop :-(

________________________________

**Comment by stefanov-stefan** [comment]
I will see if I can add more tags to the package, meanwhile search for "telerik universal"
