### ISSUE TITLE
Calling RadDataGrid.SelectItem in extended selection mode clears the selection

### ISSUE THREAD

**Issue by Zofware** [telerik/UI-For-UWP#462]
### Description
Calling RadDataGrid.SelectItem in extended selection mode clears the selection. 

### Steps to Reproduce

1. Create a RadDataGrid with SelectionMode="Extended".
2. Add some items to the grid.
3. Call SelectItem on one of the items you added.

### Expected Behavior
The desired item should be selected (and stay selected).

### Actual Behavior
The item is momentarily selected before the entire selection is cleared.

I think this is why. In RadDataGrid.Selection.cs, the implementation of SelectItem is:

```
        public void SelectItem(object item)
        {
            this.selectionService.SelectItem(item, true, false);
            this.UpdateItemToSelectFrom(item);
        }
```

But UpdateItemToSelectFrom immediately clears the selection when the SelectionMode is Extended.

```
        private void UpdateItemToSelectFrom(object item)
        {
            if (this.SelectionMode == DataGridSelectionMode.Extended)
            {
                this.selectionService.ClearSelection();
            }

            this.itemToSelectFrom = item;
        }
```

That doesn't seem right. I can take a crack at fixing this but I'm afraid of causing side effects. The Deselect* methods just modify itemToSelectFrom directly without calling UpdateItemToSelectFrom. Should SelectItem (and SelectCell) do the same?

### Basic Information

- Version with issue: 1.0.1.9
- Last known good version: unknown
- IDE: VS2019
- UWP SDK: 18362
- Nuget Packages: Will provide list if relevant to this bug but I don't think it is.

### Screenshots

Can provide if necessary

### Reproduction Link

Can provide if necessary

**Comment by APopatanasov** [comment]
Hi @Zofware,

Your observations are absolutely right. The selection should be cleared for the Extended selection mode when SelectItem/Cell gets invoked, but that should happen before selecting the desired item/cell.

I will check the pul request and will let you know if everything is good.

Thank you for your contribution.
