### ISSUE TITLE
PieChart rendering is broken with .Net Native 1.6 on ARM platform

### ISSUE THREAD

**Issue by VitalyKnyazev** [telerik/UI-For-UWP#47]
Due to an optimizer bug in .Net Native 1.6 PieChart is not rendered properly.

Prerequisites:
- Visual Studio 2017;
- Latest Microsoft.NETCore.UniversalWindowsPlatform package (v5.3.x);
- Build in Release mode with enabled .Net Native tool chain;
- Run on mobile, i.e. ARM platform (it works ok on x86).

Not that it is Telerik bug, but there is an easy and safe workaround until MS releases a fix.

**Comment by APopatanasov** [comment]
@VitalyKnyazev the fix has been merged. I will close the issue. Thanks. 😄
