### ISSUE TITLE
Chart For WinUI

### ISSUE THREAD

**Issue by sigmarsson** [telerik/UI-For-UWP#471]
Do you plan to add chart controls to WinUI? if so, will you release it in either the community or the commercial channel?

**Comment by kalintodorov** [comment]
Hi,

We already have preview version of WinUI controls suite - [Telerik UI for WinUI](https://www.telerik.com/winui), for the moment it contains the following components: Barcode, Charts, Gauges, Bulletgraph and the DataGrid control.

You can also check out the examples application that can be downloaded from [here](https://demos.telerik.com/winui/).

If you have any feedback regarding Telerik UI for WinUI you can contact us by email at TelerikWinUI@progress.com or through the [feedback portal](https://feedback.telerik.com/winui).

About the last question - once the official version framework is released, Telerik UI for WinUI will be available through our commercial channel. 

Hope this helps,
Kalin

**Comment by sigmarsson** [comment]
Howdy Kalin,

WinUI , by default is a .net5.0 project. will you publish a .net5.0 compatible package as well ?

**Comment by kalintodorov** [comment]
We are working on providing Win32 support as well, however it is not available yet due to framework limitation and issues. Will be included as soon as possible in the next releases.

-Kalin

**Comment by sigmarsson** [comment]
Is it possible to migrate only the Chart related snippets from the open source Telerik UWP Controls GitHub ?

**Comment by kalintodorov** [comment]
Hi again,

I'm sorry for the delay, There were some framework issues with the Chart project, so I'm not sure if it is possible at the current WinUI Win32 stage.

Hope this helps,
Kalin
