### ISSUE TITLE
Please provide access to the filtered item collection in the rad data grid. 

### ISSUE THREAD

**Issue by Going-Gone** [telerik/UI-For-UWP#472]
## Summary
Currently, there is no method to simply gather the items that are shown in the grid after a filter is applied. 

## API Changes

Provide a public readonly property that stores only items in the filtered collection.

## Intended Use Case
User wants to see totals in a textbox from values in the grid. 
When filter is applied another property is updated to reflect the values from the filtered collection.

**Comment by APopatanasov** [comment]
Hi @Going-Gone ,

The DataGrid control already provides an API through which you can get the items that are visualized after filtering, sorting or grouping is applied - it is called DataView. Using the Items property of the DataView you can get the items that remain after some of the above mentioned data operations is performed.

More detailed information you can find in the UI for UWP documentation:
https://docs.telerik.com/devtools/universal-windows-platform/controls/raddatagrid/features/dataview

I hope the provided information will be helpful for you.

**Comment by Going-Gone** [comment]
> Hi @Going-Gone ,
> 
> The DataGrid control already provides an API through which you can get the items that are visualized after filtering, sorting or grouping is applied - it is called DataView. Using the Items property of the DataView you can get the items that remain after some of the above mentioned data operations is performed.
> 
> More detailed information you can find in the UI for UWP documentation:
> https://docs.telerik.com/devtools/universal-windows-platform/controls/raddatagrid/features/dataview
> 
> I hope the provided information will be helpful for you.

When the filter is applied while using the FilterDescriptors.CollectionChanged event to capture it, the items dont change until after the event. Is there another event I can use to capture changed results?

**Comment by APopatanasov** [comment]
If you want to get the filtered items after the filtering operation is completed you can use the IsDataReady property of DataView to wait until the results are ready or to use the DataBindingComplete event or command - as stated in the documentation.

**Comment by Going-Gone** [comment]
> If you want to get the filtered items after the filtering operation is completed you can use the IsDataReady property of DataView to wait until the results are ready or to use the DataBindingComplete event or command - as stated in the documentation.

Thank you, appreciate the help.
