### ISSUE TITLE
The "documentation" has no relation with objects from namespaces  Telerik.UI.Xaml.Controls.Chart

### ISSUE THREAD

**Issue by DkmS1953** [telerik/UI-For-UWP#490]
### Description
[Documentation](https://docs.telerik.com/devtools/universal-windows-platform/controls/radchart/overview) is very outdated, as a result it is almost impossible to use objects.

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- UWP SDK:   
- Nuget Packages:

**Comment by didiyordanova** [comment]
Hi @DkmS1953,

For issues related to the Telerik UI for UWP documentation could you please use the Telerik UI for UWP Documentation GitHub repo: https://github.com/telerik/uwp-docs/issues/new  
You can also help us improve the documentation by submitting a pull request with the changes. For more details please check the [Help Us Improve the Telerik UI for UWP Documentation section](https://docs.telerik.com/devtools/universal-windows-platform/introduction-uwp#help-us-improve-the-telerik-ui-for-universal-windows-platform-documentation)

The [Telerik UI for UWP GitHub repo](https://github.com/telerik/UI-For-UWP) has the source code and the SDK examples for Telerik UI for UWP controls. 
I have added label documentation and closed this issue, as it is not related to the Telerik UI for UWP source code. 

Regards,
Didi
