### ISSUE TITLE
Thrown IndexOutOfRangeException when GroupDescriptors has no any items

### ISSUE THREAD

**Issue by takuya-takeuchi** [telerik/UI-For-UWP#507]
### Description

Throw exception when reload item source when using Grouping

### Steps to Reproduce

1. Set Grouping column
2. Clear Grouping column from code (Invoke RadDataGrid.GroupDescriptors.Clear())
3. Reload Item source

### Expected Behavior

No throw exception

### Actual Behavior

````
   場所 System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   場所 System.Collections.Generic.List`1.get_Item(Int32 index)
   場所 Telerik.UI.Xaml.Controls.Grid.XamlGridRowGenerator.PrepareGroupRow(GridRowModel decorator, DataGridGroupHeader groupHeader)
   場所 Telerik.UI.Xaml.Controls.Grid.RowModelPool.GenerateAndPrepareContainer(ItemInfo& itemInfo)
   場所 Telerik.UI.Xaml.Controls.Grid.NodePool`2.GenerateContainer(IList`1 itemInfos)
   場所 Telerik.UI.Xaml.Controls.Grid.NodePool`2.MeasureForward(MeasureContext& context)
   場所 Telerik.UI.Xaml.Controls.Grid.NodePool`2.MeasureVertically(RadSize availableSize, Double offset, Double bufferScale)
   場所 Telerik.UI.Xaml.Controls.Grid.NodePool`2.OnMeasure(RadSize availableSize, Double offset, Int32 frozenElementsCount, Double verticalBufferScale)
   場所 Telerik.UI.Xaml.Controls.Grid.Model.GridModel.MeasureCells(RadSize newAvailableSize)
   場所 Telerik.UI.Xaml.Controls.Grid.RadDataGrid.OnCellsPanelMeasure(RadSize newAvailableSize)
   場所 Telerik.UI.Xaml.Controls.Grid.Primitives.DataGridCellsPanel.MeasureOverride(Size availableSize)
````

https://github.com/telerik/UI-For-UWP/blob/1.0.1.8/Controls/Grid/Grid.UWP/View/ContainerGenerators/XamlGridRowGenerator.cs#L213

I'm not sure why library try to access to empty GroupDescriptors.

`Descriptor = this.owner.GroupDescriptors[decorator.ItemInfo.Level],` 

### Basic Information

- Version with issue: 1.0.1.8
- Last known good version: 1.0.1.8
- IDE: Visual Studio 2022
- UWP SDK: 17763-17763
- Nuget Packages: 1.0.1.8

### Screenshots

N/A

### Reproduction Link

N/A

**Comment by vvgeorgiev** [comment]
@takuya-takeuchi Following your description, the control works as expected on my side. Can you please provide a sample, reproducing the observed behavior?

**Comment by takuya-takeuchi** [comment]
@vvgeorgiev 
Sorry. We was not able to reproduce sample program.
So We plan to fix XamlGridRowGenerator.cs#L213](https://github.com/telerik/UI-For-UWP/blob/1.0.1.8/Controls/Grid/Grid.UWP/View/ContainerGenerators/XamlGridRowGenerator.cs#L213.

Thanks.
