### ISSUE TITLE
RadDataGrid nested Binding not working

### ISSUE THREAD

**Issue by JaggerJo** [telerik/UI-For-UWP#64]
Binding does not work if I try to bind to it like this:

`<telerik:DataGridTextColumn PropertyName="Computer.Manufacturer" Header="Computer Manufacturer"/>`

in this case Computer is a Object that Contains a property named Manufacturer of type string.

Telerik Version: 1.0.0.1

**Comment by busitech** [comment]
Will this be implemented?

**Comment by JaggerJo** [comment]
Currently I use https://docs.microsoft.com/en-us/windows/uwpcommunitytoolkit/controls/datagrid which is in a preview state, but works fine

**Comment by APopatanasov** [comment]
Hi @busitech ,

Adding this functionality to the DataGrid is marked with high priority. We will do our best to provide it with the next official release.😄
