### ISSUE TITLE
Chart issues on Windows ver. 1703 (Creators Update)

### ISSUE THREAD

**Issue by Hujerek** [telerik/UI-For-UWP#66]
This issue was initially observed on Redstone 2 Insider builds but now, when the CU is out and official, the problem still persists. See [here](http://www.telerik.com/forums/uwp-c-windows-10-redstone-2-chart-issues-a417e24408bf)

I have similar problem on my own app in Debug and Release/Native too. Missing parts of series-line, bad colors of axis etc. The same when sources from repository are used (and build) and when using original (purchased) version. Everything was fine before W10 v.1703.
See screenshot: 
![charts-ok](https://cloud.githubusercontent.com/assets/26966273/24755261/bb3eddd2-1ad9-11e7-91f2-1beaa72bafcd.png)

![charts-bug](https://cloud.githubusercontent.com/assets/26966273/24755285/d6831e32-1ad9-11e7-864e-68d9eaa0ed26.png)

**Comment by Hujerek** [comment]
Issue was confirmed by Mr. Pavel R. Pavlov from Telerik.
Issue can be simply reproduced using SDKExamples.UWP project build e.g. under VS2017 for x86 and running on machine with W10 v.1703.

Hopefully this will be resolved quickly, because also already existing/submited Store apps, which are using Telerik charts, have this issue on latest Windows official build.
Is there some workaround to fix that in the code?

**Comment by Hujerek** [comment]
It looks, like the fix as of "Ves/ChartClipFix" branch is working fine.
But still there is an issue with missing (or wrong color) grid lines (dashed X grid-lines) !

**Comment by Hujerek** [comment]
For completeness, screenshots from SDKExamples running on old/new Windows 10 version to demonstrate the issue.
![gridlines-ok](https://cloud.githubusercontent.com/assets/26966273/25336566/6cb29366-28f8-11e7-8cfa-8e2dec66adec.png)
![gridlines-bug](https://cloud.githubusercontent.com/assets/26966273/25336567/6cb3d69a-28f8-11e7-9e69-fbd39947043c.png)

**Comment by stefanov-stefan** [comment]
@Hujerek Since you closed the issue, I assume it is all Ok now?

**Comment by Hujerek** [comment]
Yes, both issues we had on Creators Update regarding charts are corrected now. Thanks.
