### ISSUE TITLE
It seems the DataBoundListBox did not support virtualization

### ISSUE THREAD

**Issue by grapehunter** [telerik/UI-For-UWP#77]
I created a very simple demo to verify it. Here is the code.
```c#
public sealed partial class MainPage : Page
    {
        public TestViewModel ViewModel { get; set; }
        public MainPage()
        {
            this.InitializeComponent();
            ViewModel = new TestViewModel();
            DataboundLb.DataContext = ViewModel;
        }
    }

    public class TestViewModel
    {
        private int currentCount = 0;
        public IncrementalLoadingCollection<TModel> Months { get; set; }
        public TestViewModel()
        {
            Months = new IncrementalLoadingCollection<TModel>(this.GetMoreItems) { BatchSize = 5000 };
        }

        private async Task<IEnumerable<TModel>> GetMoreItems(uint count)
        {
            await Task.Delay(1000);
            if (this.currentCount >= 100000)
            {
                return null;
            }

            var random = new Random(Environment.TickCount);
            var result = Enumerable.Range(this.currentCount, (int)count).Select(x => new TModel { Label = "item " + x.ToString(), Height = random.Next(50, 150) }).ToList();
            currentCount += (int)count;
            return result;
        }
    }

    public class TModel
    {
        public string Label { get; set; }
        public int Height { get; set; }
    }
```

```xml
<Page
    x:Class="TelerikDataboundLbViewer.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TelerikDataboundLbViewer"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      xmlns:telerikDataControls="using:Telerik.UI.Xaml.Controls.Data"
      mc:Ignorable="d">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <telerikDataControls:RadDataBoundListBox Grid.Row="1"
                                                 ItemsSource="{Binding Months}"
                                                 x:Name="DataboundLb">
            <telerikDataControls:RadDataBoundListBox.ItemTemplate>
                <DataTemplate>
                    <StackPanel Margin="12,12"
                                Background="Yellow"
                                Height="{Binding Height}">
                        <TextBlock Text="{Binding Label}"
                                   HorizontalAlignment="Center"
                                   Margin="12,12" />
                    </StackPanel>
                </DataTemplate>
            </telerikDataControls:RadDataBoundListBox.ItemTemplate>
        </telerikDataControls:RadDataBoundListBox>
    </Grid>
</Page>
```

Then I run it ,  the ListBox took very long time to show the items. 
And I checked the visual tree by Live Visual Tree , I found that all 5000 items had been created.
![visual tree](https://cloud.githubusercontent.com/assets/3354458/25332747/393f7d06-291a-11e7-8e8f-5491ad7c8e44.png)

**Comment by APopatanasov** [comment]
Hi @grapehunter ,
As you are using Incremental Loading the observed by you behavior of the DataBoundListBox control is an expected one. By setting the BatchSize of the collection to 5000 you are actually telling 5000 items to be loaded in the DataBoundListBox on portions until 10000 is reached.

By loading such great amount of data it is expected a delay to be observed. Some more detailed information about the incremental loading you could find [here](http://docs.telerik.com/windows-universal/controls/raddataboundlistbox/features/databoundlistbox-datavirtualization).

**Comment by grapehunter** [comment]
If I set BatchSize to 50, then to load several pages of data , it seems working fine at a first brush.
I scrolled up and down repeatedly  by **MouseWheel** , it works fine too.

Then I tried to scroll to top **by dragging scrollbar** , I found that the virtualization was broken. All items was created .

**Comment by APopatanasov** [comment]
@grapehunter We have tested your scenario with BatchSize equals to 50 and were not able to observe any unexpected behavior - when the scrollbar is dragged more items are loaded (50 as expected).

Please, send us a video with the observed by you behavior.

**Comment by grapehunter** [comment]
Please watch the video(@google photos).
[![Sample](https://user-images.githubusercontent.com/3354458/26885001-e2ea0458-4bd3-11e7-9ce7-188eaed72b95.png)](https://goo.gl/photos/8YMKxvYYBya14Hcf6 " Click to Watch!")

**00:00:00 -> 00:00:10**  
Everything works fine. There were about 750 elements in **PART_ItemsPanel[Canvas]**, it means that about  **75 items** was constructed. 
<img width="641" alt="0010_1" src="https://user-images.githubusercontent.com/3354458/26885254-b6e1ecee-4bd4-11e7-9a09-3657f21ba4ec.PNG">

And the memory used (48MB) was also acceptable
<img width="378" alt="0010_2" src="https://user-images.githubusercontent.com/3354458/26885656-d448d8b4-4bd5-11e7-8ae6-26c1b0b80996.PNG">

**from 00:00:10** 
I scrolled up and down quickly by dragging scrollbar. The memory used was raised up to 346MB in one or two seconds, and the count of visual element in **PART_ItemsPanel[Canvas]** raised up to 5673 (about 567 items)
<img width="366" alt="0011_1" src="https://user-images.githubusercontent.com/3354458/26885768-2373ec76-4bd6-11e7-8a92-95c01376a18d.PNG">
<img width="653" alt="0011_2" src="https://user-images.githubusercontent.com/3354458/26885801-3818186e-4bd6-11e7-80cb-b7017eee552a.PNG">

**Comment by grapehunter** [comment]
@APopatanasov 
I captured video by using an older version of Snagit9 which has some bugs about high-dpi ,so the mouse position in the video was incorrect.
And I also tested the scenario with **DynamicGridVirtualizationStrategies** .

**Comment by APopatanasov** [comment]
Thanks for the provided video. We were able to reproduce the described issue.

**Comment by grapehunter** [comment]
@APopatanasov 
And I found that the virtualization will be broken If I call function below
```C#
var _scrollviewer = VisualTreeTools.FindVisualChildren<ScrollViewer>(this).First();
_scrollviewer .ChangeView(null, verticalOffset,null);
```

**Comment by APopatanasov** [comment]
@grapehunter Thanks for the additional information. When the mouse is used for scrolling internally the same method is executed and because of that it is expected the issue to be reproduced when the method is called from code-behind as well. 

The information will of great help and a start point if someone from the community is interested in working on the issue.
