### ISSUE TITLE
InvalidCastException: Specified cast is not valid

### ISSUE THREAD

**Issue by schnitty** [telerik/UI-For-UWP#83]
An exception is thrown when I try to expand the "Miscellaneous" property group in the Visual Studio 2017 designer property window.

Steps to reproduce:
New UWP solution, blank page, add Telerik.UI.for.UniversalWindowsPlatform 1.0.0.1 package and then place new RadDataGrid control on page.  With the grid selected go to the properties window and expand the Miscellaneous properties group and exception is thrown

InvalidCastException: Specified cast is not valid

StackTrace
at Telerik.UI.Xaml.Controls.Grid.RadDataGrid.get_RealizedItemsVerticalBufferScale()
InnerException: None

**Comment by jmottone** [comment]
I am having the same issue in the VS 2015 Designer, but it only happens when I click on the control in the designer. I am using Telerik UI For Universal Windows Platform R2 2017 SP1...

[VS2015 SAME ERROR IN DESIGNER.zip](https://github.com/telerik/UI-For-UWP/files/1198574/VS2015.SAME.ERROR.IN.DESIGNER.zip)

**Comment by APopatanasov** [comment]
Hi @jmottone ,
I have applied a small fix for the observed by you issue. Once the pull request is merged you could give a try to the fix. IF everything is working as expected the fix will be available in the next release as well.

**Comment by jmottone** [comment]
@APopatanasov, thanks so much for getting to this so quickly, I am actually a paid user, and this was faster than the ticket system! I will give it a try when I make it back around to that project. I'm working on a WPF project at the moment...Thanks again!

**Comment by stefanov-stefan** [comment]
@jmottone the team that helps here, including @APopatanasov is handing the ticketing system as well, so we can't really say its faster here.
